using System.Linq;
using System.Numerics;
using System.Text;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared._Onyx.ZLevels.Core.Components; // <Onyx-ZLevels>
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class DockingScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    private readonly SharedShuttleSystem _shuttles;

    /// <summary>
    /// Stored by GridID then by docks
    /// </summary>
    public Dictionary<NetEntity, List<DockingPortState>> Docks = new();

    /// <summary>
    /// Store the dock buttons for the side buttons.
    /// </summary>
    private readonly Dictionary<NetEntity, Button> _ourDockButtons = new();
    private EntityUid? _consoleShuttle; // <Onyx-ZLevels>
    private EntityUid? _selectedLayer; // <Onyx-ZLevels>

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;

    public DockingScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _shuttles = _entManager.System<SharedShuttleSystem>();

        DockingControl.OnViewDock += OnView;
        DockingControl.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };
        DockingControl.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };
    }

    private void OnView(NetEntity obj)
    {
        if (_ourDockButtons.TryGetValue(obj, out var viewed))
        {
            viewed.Pressed = true;
        }
    }

    public void UpdateState(EntityUid? shuttle, DockingInterfaceState state)
    {
        Docks = state.Docks;
        DockingControl.DockState = state;
        // <Onyx-ZLevels-edited>
        if (_consoleShuttle != shuttle)
        {
            _consoleShuttle = shuttle;
            _selectedLayer = shuttle;
        }
        if (!IsLayerInNetwork(_selectedLayer, shuttle))
            _selectedLayer = shuttle;
        RebuildLayerSelector();
        DockingControl.GridEntity = _selectedLayer;
        BuildDocks(_selectedLayer);
        // </Onyx-ZLevels-edited>
    }

    // <Onyx-ZLevels>
    private bool IsLayerInNetwork(EntityUid? layer, EntityUid? root)
    {
        if (layer == null || root == null || !_entManager.EntityExists(layer.Value))
            return false;
        if (layer == root)
            return true;
        return _entManager.TryGetComponent(root.Value, out CEZLinkedGridComponent? linked) &&
               linked.PeerGrids.ContainsValue(layer.Value);
    }

    private void RebuildLayerSelector()
    {
        LayerSelectorRow.RemoveAllChildren();
        if (_consoleShuttle == null ||
            !_entManager.TryGetComponent(_consoleShuttle.Value, out CEZLinkedGridComponent? linked) ||
            linked.PeerGrids.Count == 0)
        {
            LayerSelectorRow.Visible = false;
            return;
        }

        var levels = new SortedDictionary<int, EntityUid>(linked.PeerGrids) { [linked.Depth] = _consoleShuttle.Value };
        LayerSelectorRow.Visible = true;
        LayerSelectorRow.AddChild(new Label { Text = "Z:", VerticalAlignment = VAlignment.Center });
        var group = new ButtonGroup();
        foreach (var (depth, grid) in levels)
        {
            var button = new Button { Text = depth.ToString(), ToggleMode = true, Group = group, Pressed = _selectedLayer == grid };
            button.OnPressed += _ =>
            {
                _selectedLayer = grid;
                DockingControl.GridEntity = grid;
                BuildDocks(grid);
            };
            LayerSelectorRow.AddChild(button);
        }
    }
    // </Onyx-ZLevels>

    private void BuildDocks(EntityUid? shuttle)
    {
        DockingControl.BuildDocks(shuttle);
        var currentDock = DockingControl.ViewedDock;
        // DockedWith.RemoveAllChildren();
        DockPorts.RemoveAllChildren();
        _ourDockButtons.Clear();

        if (shuttle == null)
        {
            DockingControl.SetViewedDock(null);
            return;
        }

        var shuttleNent = _entManager.GetNetEntity(shuttle.Value);

        if (!Docks.TryGetValue(shuttleNent, out var shuttleDocks) || shuttleDocks.Count <= 0)
        { // <Onyx-ZLevels-edited>
            DockingControl.SetViewedDock(null);
            return;
        } // </Onyx-ZLevels-edited>

        var dockText = new StringBuilder();
        var buttonGroup = new ButtonGroup();
        var idx = 0;
        var selected = false;

        // Build the dock buttons for our docks.
        foreach (var dock in shuttleDocks)
        {
            idx++;
            dockText.Clear();
            dockText.Append(dock.Name);

            var button = new Button()
            {
                Text = dockText.ToString(),
                ToggleMode = true,
                Group = buttonGroup,
                Margin = new Thickness(0f, 3f),
            };

            button.OnMouseEntered += args =>
            {
                DockingControl.HighlightedDock = dock.Entity;
            };

            button.OnMouseExited += args =>
            {
                DockingControl.HighlightedDock = null;
            };

            button.Label.Margin = new Thickness(3f);

            if (currentDock == dock.Entity)
            {
                selected = true;
                button.Pressed = true;
            }

            button.OnPressed += args =>
            {
                OnDockPress(dock);
            };

            _ourDockButtons[dock.Entity] = button;
            DockPorts.AddChild(button);
        }

        // Button group needs one selected so just show the first one.
        if (!selected)
        {
            var buttonOne = shuttleDocks[0];
            OnDockPress(buttonOne);
        }

        var shuttleContainers = new Dictionary<NetEntity, DockObject>();

        foreach (var dock in shuttleDocks.OrderBy(x => x.GridDockedWith))
        {
            if (dock.GridDockedWith == null)
                continue;

            DockObject? dockContainer;

            if (!shuttleContainers.TryGetValue(dock.GridDockedWith.Value, out dockContainer))
            {
                dockContainer = new DockObject();
                shuttleContainers[dock.GridDockedWith.Value] = dockContainer;
                var dockGrid = _entManager.GetEntity(dock.GridDockedWith);
                string? iffLabel = null;

                if (_entManager.EntityExists(dockGrid))
                {
                    iffLabel = _shuttles.GetIFFLabel(dockGrid.Value);
                }

                iffLabel ??= Loc.GetString("shuttle-console-unknown");
                dockContainer.SetName(iffLabel);
                // DockedWith.AddChild(dockContainer);
            }

            dockContainer.AddDock(dock, DockingControl);
        }
    }

    private void OnDockPress(DockingPortState state)
    {
        DockingControl.SetViewedDock(state);
    }
}
