using System.Globalization;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Communications;
using Content.Shared._Onyx.Screens;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Communications;

[GenerateTypedNameReferences]
public sealed partial class OnyxCommunicationsConsoleMenu : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;
    private readonly BoxContainer[] _screens;
    private readonly ButtonGroup _alertLevelGroup = new();
    private readonly Popup _alertLevelsPopup;
    private readonly BoxContainer _alertLevels = new() { Orientation = BoxContainer.LayoutOrientation.Vertical };
    private Entity<OnyxCommunicationsConsoleComponent>? _console;
    private string _line1 = string.Empty;
    private string _line2 = string.Empty;

    public event Action<BoundUserInterfaceMessage>? OnMessage;

    public OnyxCommunicationsConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _screens = [HomeScreen, AnnouncementScreen, ScreenScreen, ShuttlesScreen, AlertLevelScreen];
        HomeButton.OnPressed += _ => SetScreen(HomeScreen);
        AnnouncementTab.OnPressed += _ => SetScreen(AnnouncementScreen);
        ScreenTab.OnPressed += _ => SetScreen(ScreenScreen);
        ShuttlesTab.OnPressed += _ => SetScreen(ShuttlesScreen);
        AlertLevelTab.OnPressed += _ => SetScreen(AlertLevelScreen);
        foreach (var content in Enum.GetValues<StatusDisplayContent>())
            ScreenContentsButton.AddItem(Loc.GetString($"comms-console-menu-screen-content.{content}"), (int) content);
        AnnounceButton.OnPressed += _ => OnMessage?.Invoke(new CommunicationsConsoleAnnouncementMessage(Rope.Collapse(AnnounceInput.TextRope)));
        ScreenUpdateTextButton.OnPressed += _ => UpdateScreen();
        ScreenContentsButton.OnItemSelected += args => { ScreenContentsButton.SelectId(args.Id); UpdateScreen(); };
        ScreenAlertBorder.OnToggled += _ => UpdateScreen();
        ShuttleEmergencyButton.OnPressed += _ => OnMessage?.Invoke(new CommunicationsConsoleEvacuationShuttleMessage(_console?.Comp.ExpectedEvacuationArrival is null));
        AlertLevelsDropdown.OnPressed += OpenAlertLevels;
        _alertLevelsPopup = new() { Children = { _alertLevels } };
        _alertLevelsPopup.OnPopupHide += _alertLevelsPopup.Orphan;
        AnnounceInput.Placeholder = new Rope.Leaf(Loc.GetString("comms-console-menu-announcement-placeholder"));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_console is not { } console)
            return;
        AnnounceButton.Disabled = _timing.CurTime <= console.Comp.CanAnnounceAt;
        AlertLevelsDropdown.Disabled = console.Comp.CanSetAlertAt is null || _timing.CurTime <= console.Comp.CanSetAlertAt;
        if (console.Comp.ExpectedEvacuationArrival is { } arrival)
            EmergencyStatus.Text = Loc.GetString("comms-console-menu-shuttle-eta", ("time", MathHelper.Max(arrival - _timing.CurTime, TimeSpan.Zero).ToString(@"hh\:mm\:ss", CultureInfo.CurrentCulture)));
        else
            EmergencyStatus.Text = Loc.GetString("comms-console-menu-shuttle-not-coming");
    }

    public void Update(Entity<OnyxCommunicationsConsoleComponent> console)
    {
        _console = console;
        AnnouncementTab.Visible = console.Comp.CanAnnounce;
        ScreenTab.Visible = console.Comp.CanConfigureScreens;
        ShuttlesTab.Visible = console.Comp.CanCallShuttles;
        AlertLevelTab.Visible = console.Comp.CanAlertLevel;
        if (console.Comp.CanAnnounce && !(console.Comp.CanAlertLevel || console.Comp.CanCallShuttles || console.Comp.CanConfigureScreens))
        {
            SetScreen(AnnouncementScreen);
            HomeButton.Visible = false;
        }
        ShuttleEmergencyButton.Disabled = !console.Comp.ShuttlesCallable;
        ShuttleEmergencyButton.Text = Loc.GetString($"comms-console-menu-call-emergency.{console.Comp.ExpectedEvacuationArrival is null}");
        _alertLevels.RemoveAllChildren();
        foreach (var level in console.Comp.AlertLevels)
        {
            if (level.Id == console.Comp.CurrentAlertLevel)
                AlertLevel.Text = Loc.GetString("comms-console-menu-current-alert-level", ("name", Loc.GetString(level.AlertLevel)), ("color", level.Color), ("description", Loc.GetString(level.Description)));
            if (!level.CanSet)
                continue;
            var button = new Button { Text = Loc.GetString(level.AlertLevel), ToggleMode = true, Group = _alertLevelGroup, Pressed = level.Id == console.Comp.CurrentAlertLevel };
            _alertLevels.AddChild(button);
            button.OnPressed += _ => { _alertLevelsPopup.Close(); OnMessage?.Invoke(new CommunicationsConsoleAlertLevelMessage(level.Id)); };
        }
        if (console.Comp.LastConfiguredLine1 != _line1) ScreenLine1.Text = console.Comp.LastConfiguredLine1;
        if (console.Comp.LastConfiguredLine2 != _line2) ScreenLine2.Text = console.Comp.LastConfiguredLine2;
        ScreenContentsButton.SelectId((int) console.Comp.LastConfiguredContent);
        ScreenAlertBorder.Pressed = console.Comp.LastConfiguredShowBorders;
        _line1 = console.Comp.LastConfiguredLine1;
        _line2 = console.Comp.LastConfiguredLine2;
    }

    private void SetScreen(Control screen) { foreach (var other in _screens) other.Visible = false; screen.Visible = true; HomeButton.Visible = screen != HomeScreen; }
    private void UpdateScreen() => OnMessage?.Invoke(new CommunicationsConsoleScreenConfigurationMessage((StatusDisplayContent) ScreenContentsButton.SelectedId, ScreenAlertBorder.Pressed, ScreenLine1.Text, ScreenLine2.Text));
    private void OpenAlertLevels(BaseButton.ButtonEventArgs args) { var position = AlertLevelsDropdown.GlobalPosition; position.Y += AlertLevelsDropdown.Size.Y + 1; _alertLevels.Measure(Window?.Size ?? Vector2Helpers.Infinity); _alertLevelsPopup.Orphan(); Root?.ModalRoot.AddChild(_alertLevelsPopup); _alertLevelsPopup.Open(UIBox2.FromDimensions(position, new Vector2(Math.Max(_alertLevels.DesiredSize.X, AlertLevelsDropdown.Width), _alertLevels.DesiredSize.Y))); }
}
