using Content.Shared._Onyx.Targeting;
using Content.Shared.Damage;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Targeting.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerStatusDoll : UIWidget
{
    private readonly IResourceCache _resources = IoCManager.Resolve<IResourceCache>();
    private readonly Dictionary<TargetBodyPart, PartControl> _parts;

    public event Action<TargetBodyPart>? PartSelected;

    public HealthAnalyzerStatusDoll()
    {
        RobustXamlLoader.Load(this);
        _parts = new Dictionary<TargetBodyPart, PartControl>
        {
            [TargetBodyPart.Head] = new(DollHead, HeadButton, "head"),
            [TargetBodyPart.Chest] = new(DollChest, ChestButton, "chest", "torso"),
            [TargetBodyPart.Groin] = new(DollGroin, GroinButton, "groin"),
            [TargetBodyPart.LeftArm] = new(DollLeftArm, LeftArmButton, "leftarm"),
            [TargetBodyPart.LeftHand] = new(DollLeftHand, LeftHandButton, "lefthand"),
            [TargetBodyPart.RightArm] = new(DollRightArm, RightArmButton, "rightarm"),
            [TargetBodyPart.RightHand] = new(DollRightHand, RightHandButton, "righthand"),
            [TargetBodyPart.LeftLeg] = new(DollLeftLeg, LeftLegButton, "leftleg"),
            [TargetBodyPart.LeftFoot] = new(DollLeftFoot, LeftFootButton, "leftfoot"),
            [TargetBodyPart.RightLeg] = new(DollRightLeg, RightLegButton, "rightleg"),
            [TargetBodyPart.RightFoot] = new(DollRightFoot, RightFootButton, "rightfoot"),
        };

        foreach (var (part, data) in _parts)
        {
            data.Button.ToolTip = Loc.GetString($"targeting-part-{PartKey(part)}");
            data.Button.OnPressed += _ => PartSelected?.Invoke(part);
            data.Button.OnMouseEntered += _ => SetButtonTexture(data, true);
            data.Button.OnMouseExited += _ => SetButtonTexture(data, false);
        }
    }

    public void Refresh(
        IReadOnlyDictionary<TargetBodyPart, DamageSpecifier> damage,
        SpriteSystem sprites)
    {
        foreach (var (part, data) in _parts)
        {
            var exists = damage.TryGetValue(part, out var partDamage);
            var severity = exists
                ? (int) PartStatusSystem.GetSeverity(partDamage!.GetTotal().Float())
                : 6;
            data.Status.Texture = sprites.Frame0(new SpriteSpecifier.Rsi(
                new ResPath($"/Textures/_Onyx/Interface/Targeting/Status/{data.StatusState}.rsi"),
                $"{data.StatusState}_{severity}"));
            data.Button.Disabled = !exists;
            SetButtonTexture(data, data.Button.IsHovered);
        }
    }

    private void SetButtonTexture(PartControl data, bool hovered)
    {
        if (data.Button.Disabled || !hovered)
        {
            data.Button.TextureNormal = null;
            return;
        }

        var suffix = hovered ? "_hover" : string.Empty;
        data.Button.TextureNormal = _resources
            .GetResource<TextureResource>($"/Textures/_Onyx/Interface/Targeting/Doll/{data.DollState}{suffix}.png").Texture;
    }

    private static string PartKey(TargetBodyPart part) => part.ToString()
        .Replace("Left", "left-")
        .Replace("Right", "right-")
        .ToLowerInvariant();

    private sealed class PartControl(
        TextureRect status,
        TextureButton button,
        string statusState,
        string? dollState = null)
    {
        public TextureRect Status { get; } = status;
        public TextureButton Button { get; } = button;
        public string StatusState { get; } = statusState;
        public string DollState { get; } = dollState ?? statusState;
    }
}
