using Content.Shared._Onyx.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Targeting.UI;

[GenerateTypedNameReferences]
public sealed partial class PartStatusControl : UIWidget
{
    private readonly Dictionary<TargetBodyPart, (TextureRect Control, string State)> _parts;
    public event Action? ExamineRequested;

    public PartStatusControl()
    {
        RobustXamlLoader.Load(this);
        _parts = new Dictionary<TargetBodyPart, (TextureRect, string)>
        {
            [TargetBodyPart.Head] = (DollHead, "head"),
            [TargetBodyPart.Chest] = (DollChest, "chest"),
            [TargetBodyPart.Groin] = (DollGroin, "groin"),
            [TargetBodyPart.LeftArm] = (DollLeftArm, "leftarm"),
            [TargetBodyPart.LeftHand] = (DollLeftHand, "lefthand"),
            [TargetBodyPart.RightArm] = (DollRightArm, "rightarm"),
            [TargetBodyPart.RightHand] = (DollRightHand, "righthand"),
            [TargetBodyPart.LeftLeg] = (DollLeftLeg, "leftleg"),
            [TargetBodyPart.LeftFoot] = (DollLeftFoot, "leftfoot"),
            [TargetBodyPart.RightLeg] = (DollRightLeg, "rightleg"),
            [TargetBodyPart.RightFoot] = (DollRightFoot, "rightfoot"),
        };
        MouseFilter = MouseFilterMode.Stop;
        OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.Use)
                ExamineRequested?.Invoke();
        };
    }

    public void Refresh(
        bool visible,
        IReadOnlyDictionary<TargetBodyPart, PartStatus> statuses,
        SpriteSystem sprites)
    {
        Visible = visible;
        if (!visible)
            return;

        foreach (var (part, data) in _parts)
        {
            var status = statuses.GetValueOrDefault(part, Content.Shared._Onyx.Targeting.PartStatusSystem.Missing);
            var severity = status.Exists ? (int) status.Severity : 0;
            var sprite = new SpriteSpecifier.Rsi(
                new ResPath($"/Textures/_Onyx/Interface/Targeting/Status/{data.State}.rsi"),
                $"{data.State}_{severity}");
            data.Control.Texture = sprites.Frame0(sprite);
        }
    }
}
