using Content.Shared._Onyx.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Targeting.UI;

[GenerateTypedNameReferences]
public sealed partial class TargetingControl : UIWidget
{
    private readonly IResourceCache _resourceCache = IoCManager.Resolve<IResourceCache>();
    private readonly Dictionary<TargetBodyPart, TextureButton> _buttons;
    public event Action<TargetBodyPart>? PartRequested;

    public TargetingControl()
    {
        RobustXamlLoader.Load(this);
        _buttons = new Dictionary<TargetBodyPart, TextureButton>
        {
            [TargetBodyPart.Head] = HeadButton,
            [TargetBodyPart.Chest] = ChestButton,
            [TargetBodyPart.Groin] = GroinButton,
            [TargetBodyPart.LeftArm] = LeftArmButton,
            [TargetBodyPart.LeftHand] = LeftHandButton,
            [TargetBodyPart.RightArm] = RightArmButton,
            [TargetBodyPart.RightHand] = RightHandButton,
            [TargetBodyPart.LeftLeg] = LeftLegButton,
            [TargetBodyPart.LeftFoot] = LeftFootButton,
            [TargetBodyPart.RightLeg] = RightLegButton,
            [TargetBodyPart.RightFoot] = RightFootButton,
        };

        foreach (var (part, button) in _buttons)
        {
            button.MouseFilter = MouseFilterMode.Stop;
            button.ToolTip = Loc.GetString($"targeting-part-{PartKey(part)}");
            button.OnPressed += _ => PartRequested?.Invoke(part);
            button.OnMouseEntered += _ => SetHoverTexture(part, button);
            button.OnMouseExited += _ => button.TextureNormal = null;
        }
    }

    public void Refresh(
        bool visible,
        TargetBodyPart selected,
        TargetBodyPart? pending,
        IReadOnlyDictionary<TargetBodyPart, PartStatus> statuses)
    {
        Visible = visible;
        foreach (var (part, button) in _buttons)
        {
            button.Disabled = statuses.TryGetValue(part, out var status) && !status.Exists;
            if (button.Disabled)
                button.TextureNormal = null;
            button.Children[0].Visible = (pending ?? selected) == part;
        }
    }

    private void SetHoverTexture(TargetBodyPart part, TextureButton button)
    {
        if (button.Disabled)
            return;

        var texture = part switch
        {
            TargetBodyPart.Head => "head",
            TargetBodyPart.Chest => "torso",
            TargetBodyPart.Groin => "groin",
            TargetBodyPart.LeftArm => "leftarm",
            TargetBodyPart.LeftHand => "lefthand",
            TargetBodyPart.RightArm => "rightarm",
            TargetBodyPart.RightHand => "righthand",
            TargetBodyPart.LeftLeg => "leftleg",
            TargetBodyPart.LeftFoot => "leftfoot",
            TargetBodyPart.RightLeg => "rightleg",
            TargetBodyPart.RightFoot => "rightfoot",
            _ => null,
        };

        if (texture != null)
            button.TextureNormal = _resourceCache
                .GetResource<TextureResource>($"/Textures/_Onyx/Interface/Targeting/Doll/{texture}_hover.png").Texture;
    }

    private static string PartKey(TargetBodyPart part) => part.ToString().Replace("Left", "left-").Replace("Right", "right-").ToLowerInvariant();
}
