using Content.Shared.CartridgeLoader;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.PDA;

[GenerateTypedNameReferences]
public sealed partial class ModernPdaProgramItem : ContainerButton
{
    private readonly StyleBoxFlat _background = CardStyle("#1A2026", "#00000000");
    private readonly StyleBoxFlat _iconBackground = CardStyle("#12171B", "#314038");
    private readonly StyleBoxFlat _actionBackground = ActionStyle("#20362D", "#56826E");
    private Color _themeAccent = Color.FromHex("#6B9A88");
    private Entity<CartridgeComponent> _cartridge;

    public event Action<EntityUid>? OnProgramItemPressed;
    public event Action<EntityUid>? OnUninstallButtonPressed;
    public event Action<EntityUid>? OnInstallButtonPressed;

    public ModernPdaProgramItem()
    {
        RobustXamlLoader.Load(this);
        Background.PanelOverride = _background;
        IconPanel.PanelOverride = _iconBackground;
        InstallButton.StyleBoxOverride = _actionBackground;

        OnPressed += _ => OnProgramItemPressed?.Invoke(_cartridge);
        InstallButton.OnPressed += _ => ToggleInstallation();
        InstallButton.OnMouseEntered += _ => ApplyActionStyle(true);
        InstallButton.OnMouseExited += _ => ApplyActionStyle(false);
        OnMouseEntered += _ => _background.BorderColor = _themeAccent;
        OnMouseExited += _ => _background.BorderColor = Color.Transparent;
    }

    public ModernPdaProgramItem(Entity<CartridgeComponent> program) : this()
    {
        SetCartridge(program);
    }

    public void SetTheme(Color accent)
    {
        _themeAccent = accent;
        _background.BorderColor = Color.Transparent;
        _iconBackground.BorderColor = accent;
    }

    public void SetCartridge(Entity<CartridgeComponent> program)
    {
        _cartridge = program;
        ProgramName.Text = Loc.GetString(program.Comp.ProgramName);

        if (program.Comp.Icon is { } icon)
            Icon.SetFromSpriteSpecifier(icon);

        switch (program.Comp.InstallationStatus)
        {
            case InstallationStatus.Cartridge:
                ProgramStatus.Text = Loc.GetString("pda-modern-program-cartridge");
                InstallButton.Visible = true;
                InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                ApplyActionStyle(false);
                break;
            case InstallationStatus.Installed:
                ProgramStatus.Text = Loc.GetString("pda-modern-program-installed");
                InstallButton.Visible = true;
                InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                ApplyActionStyle(false);
                break;
            case InstallationStatus.Readonly:
                ProgramStatus.Text = Loc.GetString("pda-modern-program-system");
                InstallButton.Visible = false;
                break;
        }
    }

    private void ToggleInstallation()
    {
        if (_cartridge.Comp.InstallationStatus == InstallationStatus.Cartridge)
            OnInstallButtonPressed?.Invoke(_cartridge.Owner);
        else if (_cartridge.Comp.InstallationStatus == InstallationStatus.Installed)
            OnUninstallButtonPressed?.Invoke(_cartridge.Owner);
    }

    private void ApplyActionStyle(bool hovered)
    {
        var uninstall = _cartridge.Comp.InstallationStatus == InstallationStatus.Installed;
        _actionBackground.BackgroundColor = Color.FromHex(uninstall
            ? hovered ? "#5A3035" : "#3B2529"
            : hovered ? "#315443" : "#20362D");
        _actionBackground.BorderColor = Color.FromHex(uninstall ? "#A85B65" : "#56826E");
        InstallButton.Label.FontColorOverride = Color.FromHex(uninstall ? "#F0B0B5" : "#B8E3CF");
    }

    private static StyleBoxFlat CardStyle(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
        };
    }

    private static StyleBoxFlat ActionStyle(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };
    }
}
