using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.PDA;

[GenerateTypedNameReferences]
public sealed partial class ModernPdaSettingsButton : ContainerButton
{
    private readonly StyleBoxFlat _background = new()
    {
        BackgroundColor = Color.FromHex("#1A2026"),
        BorderColor = Color.FromHex("#384550"),
        BorderThickness = new Thickness(1),
    };

    public string? Text
    {
        get => OptionName.Text;
        set => OptionName.Text = value;
    }

    public string? Description
    {
        get => OptionDescription.Text;
        set => OptionDescription.Text = value;
    }

    public ModernPdaSettingsButton()
    {
        RobustXamlLoader.Load(this);
        Background.PanelOverride = _background;
    }

    public void SetTheme(Color accent)
    {
        _background.BorderColor = accent;
    }
}
