// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 pheenty <fedorlukin2006@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.SetSelector;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.SetSelector;

[GenerateTypedNameReferences]
public sealed partial class SetSelectorMenu : FancyWindow
{
    [Dependency] private IEntitySystemManager _sysMan = default!;
    private readonly SpriteSystem _spriteSystem;

    public event Action? OnApprove;
    public event Action<int>? OnSetChange;

    public SetSelectorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _sysMan.GetEntitySystem<SpriteSystem>();
        ApproveButton.OnPressed += _ => OnApprove?.Invoke();
    }

    public void UpdateState(SetSelectorBoundUserInterfaceState state)
    {
        SetsGrid.DisposeAllChildren();
        var selectedCount = 0;
        foreach (var (index, info) in state.Sets)
        {
            var child = new SelectableSet(info, _spriteSystem);
            child.SetButton.OnButtonDown += _ => OnSetChange?.Invoke(index);
            SetsGrid.AddChild(child);

            if (info.Selected)
                selectedCount++;
        }

        Description.Text = Loc.GetString("set-selector-window-description", ("maxCount", state.MaxSelectedSets));
        SelectedSets.Text = Loc.GetString("set-selector-window-selected",
            ("selectedCount", selectedCount),
            ("maxCount", state.MaxSelectedSets));
        ApproveButton.Disabled = selectedCount != state.MaxSelectedSets;
    }
}
