using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class DestructiveAnalyzerMenu : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly ResearchSystem _research;
    private readonly List<(RichTextLabel Label, Control Container)> _wrappingLabels = new();

    public event Action? OnServerButtonPressed;
    public event Action<string>? OnMethodSelected;
    public event Action? OnAnalyzePressed;
    public event Action? OnEjectPressed;

    public DestructiveAnalyzerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entManager.System<ResearchSystem>();

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        AnalyzeButton.OnPressed += _ => OnAnalyzePressed?.Invoke();
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
        MethodOption.OnItemSelected += args =>
        {
            if (MethodOption.GetItemMetadata(args.Id) is not string id)
                return;

            OnMethodSelected?.Invoke(id);
        };

        // RichTextLabel wraps against the width it receives during measurement.
        // Each label is measured against its own section container, so text
        // reflows on resize instead of getting clipped. Wrapping labels never
        // share a horizontal row with fixed-width elements.
        RegisterWrap(BalanceLabel, ServerContainer);
        RegisterWrap(InsertedItemLabel, SampleContainer);
        RegisterWrap(LastSubjectLabel, LogContainer);
        RegisterWrap(LastResultLabel, LogContainer);
    }

    private void RegisterWrap(RichTextLabel label, Control container)
    {
        label.HorizontalExpand = true;
        label.HorizontalAlignment = HAlignment.Stretch;
        _wrappingLabels.Add((label, container));
        container.OnResized += UpdateWrapping;
    }

    private void UpdateWrapping()
    {
        foreach (var (label, container) in _wrappingLabels)
        {
            var width = container.Size.X - 2f;
            if (width <= 8f)
                continue;

            if (!MathHelper.CloseTo(label.SetWidth, width))
                label.SetWidth = width;
        }
    }

    private string LocalizeMethod(string methodId)
    {
        const string revealPrefix = "reveal:";
        if (methodId.StartsWith(revealPrefix, StringComparison.Ordinal))
        {
            var technologyId = methodId[revealPrefix.Length..];
            var technologyName = _prototype.TryIndex<TechnologyPrototype>(technologyId, out var technology)
                ? Loc.GetString(technology.Name)
                : technologyId;
            return Loc.GetString("research-machine-destructive-method-reveal-technology",
                ("technology", technologyName));
        }

        return Loc.TryGetString($"research-machine-destructive-method-{methodId.ToLowerInvariant()}", out var localized)
            ? localized
            : Loc.GetString("research-machine-destructive-method-unknown");
    }

    private static void SetPlainText(RichTextLabel label, string text)
    {
        label.SetMessage(FormattedMessage.FromUnformatted(text));
    }

    public void UpdateState(DestructiveAnalyzerBoundInterfaceState state)
    {
        ServerLabel.Text = state.ConnectedServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", state.ConnectedServerName));

        BalanceLabel.SetMessage(state.PointBalances.Count > 0
            ? FormattedMessage.FromMarkupOrThrow(Loc.GetString(
                "research-console-menu-research-points-balances-text",
                ("balances", ResearchPointUiHelpers.BuildBalanceMarkup(state.PointBalances, _research, _prototype))))
            : FormattedMessage.Empty);

        SetPlainText(InsertedItemLabel, Loc.GetString("research-machine-common-labeled-value",
            ("label", Loc.GetString("research-machine-common-last-subject")),
            ("value", state.InsertedItem ?? Loc.GetString("research-machine-common-none"))));

        if (state.InsertedItemEntity is { } net && _entManager.TryGetEntity(net, out var uid))
            InsertedItemSprite.SetEntity(uid);
        else
            InsertedItemSprite.SetEntity(null);

        MethodOption.Clear();
        for (var i = 0; i < state.Methods.Count; i++)
        {
            var method = state.Methods[i];
            MethodOption.AddItem(LocalizeMethod(method), i);
            MethodOption.SetItemMetadata(i, method);
            if (method == state.SelectedMethod)
                MethodOption.SelectId(i);
        }
        AnalyzeButton.Disabled = state.Methods.Count == 0;

        var subject = string.IsNullOrWhiteSpace(state.LastSubject)
            ? Loc.GetString("research-machine-common-none")
            : state.LastSubject;
        SetPlainText(LastSubjectLabel, $"{Loc.GetString("research-machine-common-last-subject")}: {subject}");

        var result = string.IsNullOrWhiteSpace(state.LastResult)
            ? Loc.GetString("research-machine-common-none")
            : state.LastResult;
        SetPlainText(LastResultLabel, $"{Loc.GetString("research-machine-common-last-result")}: {result}");

        EjectButton.Disabled = state.InsertedItem == null;
    }
}
