using System.Numerics;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleItem : LayoutContainer
{
    public readonly TechnologyPrototype Prototype;
    public readonly Vector2 TreePosition;
    public event Action<TechnologyPrototype, ResearchAvailability>? SelectAction;
    public readonly ResearchAvailability Availability;

    private Color _color;
    private Color _hoveredColor;
    private Color _borderColor;

    public FancyResearchConsoleItem(TechnologyPrototype proto, Vector2 position, SpriteSystem sprite, ResearchAvailability availability)
    {
        RobustXamlLoader.Load(this);
        Prototype = proto;
        TreePosition = position;
        Availability = availability;
        ResearchDisplay.Texture = sprite.Frame0(proto.Icon);
        Button.OnDrawModeChanged += UpdateColor;
        Button.OnPressed += Selected;

        (_color, _hoveredColor, _borderColor) = availability switch
        {
            ResearchAvailability.Researched => (Color.DarkOliveGreen, Color.PaleGreen, Color.LimeGreen),
            ResearchAvailability.Available => (Color.FromHex("#7c7d2a"), Color.FromHex("#ecfa52"), Color.FromHex("#e8fa25")),
            ResearchAvailability.PrereqsMet => (Color.FromHex("#6b572f"), Color.FromHex("#fad398"), Color.FromHex("#cca031")),
            _ => (Color.DarkRed, Color.PaleVioletRed, Color.Crimson)
        };
        UpdateColor();
    }

    private void UpdateColor()
    {
        var panel = (StyleBoxFlat) Panel.PanelOverride!;
        panel.BackgroundColor = Button.IsHovered ? _hoveredColor : _color;
        panel.BorderColor = _borderColor;
    }

    private void Selected(BaseButton.ButtonEventArgs args) => SelectAction?.Invoke(Prototype, Availability);

    public void SetScale(float scale) => ((BoxContainer) GetChild(0)).SetSize = new Vector2(80 * scale);

    public void SetFiltered(bool filtered) => FilterOverlay.Visible = filtered;

    protected override void ExitedTree()
    {
        Button.OnDrawModeChanged -= UpdateColor;
        Button.OnPressed -= Selected;
        base.ExitedTree();
    }
}

public sealed class DrawButton : Button
{
    public event Action? OnDrawModeChanged;

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        OnDrawModeChanged?.Invoke();
    }
}
