using System.Linq;
using System.Numerics;
using Content.Client.Research;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Research;
using Content.Shared.Access.Components;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleMenu : FancyWindow
{
    public event Action<string>? OnTechnologyCardPressed;
    public event Action? OnServerButtonPressed;

    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;
    private readonly Dictionary<string, List<TechnologyPrototype>> _technologiesByDiscipline = new();
    private readonly Dictionary<string, Button> _disciplineTabs = new();
    private readonly Dictionary<string, Label> _disciplineProgress = new();
    private readonly List<FancyResearchConsoleItem> _items = new();
    private readonly List<(TechnologyPrototype Tech, ResearchAvailability Availability)> _matches = new();
    private readonly HashSet<string> _matchIds = new();
    private ButtonGroup _disciplineGroup = new(isNoneSetAllowed: false);
    private FancyResearchConsoleNetworkLogWindow? _networkLogWindow;
    private List<ResearchNetworkLogEntry> _networkLogs = new();

    public Dictionary<string, ResearchAvailability> List { get; private set; } = new();
    public int Points { get; private set; }
    public EntityUid Entity { get; private set; }
    public ProtoId<TechnologyPrototype>? CurrentTech { get; private set; }

    private Vector2 _position;
    private float _zoom = 1f;
    private bool _dragging;
    private string? _selectedDiscipline;
    private string _searchText = string.Empty;
    private int _currentMatch = -1;
    private bool _initialTreePositionSet;

    public FancyResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        NetworkLogButton.OnPressed += _ => OpenNetworkLog();
        RecenterButton.OnPressed += _ => Recenter();
        CloseInfoButton.OnPressed += _ => CloseInfo();
        DragContainer.OnKeyBindDown += OnDragKeyBindDown;
        DragContainer.OnKeyBindUp += OnDragKeyBindUp;
        RecipeSearchLineEdit.OnTextChanged += OnSearchChanged;
        RecipeSearchLineEdit.OnTextEntered += OnSearchEntered;
        DragContainer.OnResized += OnDragContainerResized;
    }

    public void SetEntity(EntityUid entity) => Entity = entity;

    public void UpdatePanels(Dictionary<string, ResearchAvailability> list)
    {
        var preservePosition = _initialTreePositionSet;
        var position = _position;
        List = list;
        if (CurrentTech is { } selected && !list.ContainsKey(selected))
        {
            CurrentTech = null;
            InfoContainer.RemoveAllChildren();
        }

        _technologiesByDiscipline.Clear();
        foreach (var tech in _prototype.EnumeratePrototypes<TechnologyPrototype>().Where(tech => list.ContainsKey(tech.ID)))
        {
            if (!_technologiesByDiscipline.TryGetValue(tech.Discipline, out var technologies))
                _technologiesByDiscipline[tech.Discipline] = technologies = new();
            technologies.Add(tech);
        }

        UpdateMatches();
        UpdateDisciplineTabs();
        UpdateTree();
        if (preservePosition)
        {
            _position = position;
            RecenterItems();
        }
    }

    public void UpdateInformationPanel(int points, IReadOnlyList<ResearchPointAmount>? balances = null)
    {
        Points = points;
        ResearchAmountLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(balances is { Count: > 0 }
            ? Loc.GetString("research-console-menu-research-points-balances-text",
                ("balances", ResearchPointUiHelpers.BuildBalanceMarkup(balances, _research, _prototype)))
            : Loc.GetString("research-console-menu-research-points-text", ("points", points))));
        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        foreach (var (id, label) in _disciplineProgress)
            label.Text = $"{GetCompletion(database, id):0}%";

        if (CurrentTech is { } selected && List.TryGetValue(selected, out var availability) && _prototype.TryIndex(selected, out TechnologyPrototype? tech))
            ShowInfo(tech, availability);
    }

    private void UpdateDisciplineTabs()
    {
        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        DisciplineTabsContainer.RemoveAllChildren();
        DisciplineProgressContainer.RemoveAllChildren();
        _disciplineGroup = new ButtonGroup(isNoneSetAllowed: false);
        _disciplineTabs.Clear();
        _disciplineProgress.Clear();

        if (_selectedDiscipline == null || !_technologiesByDiscipline.ContainsKey(_selectedDiscipline))
            _selectedDiscipline = database.SupportedDisciplines.FirstOrDefault(id => _technologiesByDiscipline.ContainsKey(id));

        foreach (var id in database.SupportedDisciplines)
        {
            if (!_technologiesByDiscipline.ContainsKey(id))
                continue;

            var discipline = _prototype.Index<TechDisciplinePrototype>(id);
            var tab = new Button
            {
                Text = Loc.GetString(discipline.Name),
                ToggleMode = true,
                Group = _disciplineGroup,
                HorizontalExpand = true,
                MinHeight = 46,
                Margin = new Thickness(2),
                StyleClasses = { StyleClass.ButtonSquare }
            };
            var stripe = new StripeBack { HorizontalExpand = true, HasTopEdge = true, HasBottomEdge = true, HasMargins = true };
            stripe.AddChild(tab);
            DisciplineTabsContainer.AddChild(stripe);
            var progress = new Label { Text = $"{GetCompletion(database, id):0}%", StyleClasses = { "LabelBigBold" } };
            DisciplineProgressContainer.AddChild(new BoxContainer
            {
                Margin = new Thickness(3, 5, 9, 5),
                Children =
                {
                    new TextureRect
                    {
                        Texture = _sprite.Frame0(discipline.Icon),
                        TextureScale = new Vector2(2),
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(0, 0, 4, 0)
                    },
                    progress
                }
            });
            _disciplineTabs[id] = tab;
            _disciplineProgress[id] = progress;
            tab.OnToggled += args =>
            {
                if (!args.Pressed)
                    return;
                _selectedDiscipline = id;
                UpdateTree();
            };
        }

        if (_selectedDiscipline != null && _disciplineTabs.TryGetValue(_selectedDiscipline, out var selectedTab))
            selectedTab.Pressed = true;
    }

    private void UpdateTree()
    {
        ClearItems();
        if (_selectedDiscipline == null || !_technologiesByDiscipline.TryGetValue(_selectedDiscipline, out var technologies))
            return;

        foreach (var tech in technologies)
        {
            var treePosition = new Vector2(tech.Position.X, tech.Position.Y) * 150f;
            var item = new FancyResearchConsoleItem(tech, treePosition, _sprite, List[tech.ID]);
            item.SelectAction += SelectTech;
            item.SetFiltered(_searchText.Length > 0 && !_matchIds.Contains(tech.ID));
            item.SetScale(_zoom);
            LayoutContainer.SetPosition(item, _position + treePosition * _zoom);
            DragContainer.AddChild(item);
            _items.Add(item);
        }

        DragContainer.InvalidateMeasure();
        if (_initialTreePositionSet)
            Recenter();
        else
            Timer.Spawn(0, Recenter);
    }

    private float GetCompletion(TechnologyDatabaseComponent database, string discipline)
    {
        var total = _technologiesByDiscipline.TryGetValue(discipline, out var techs) ? techs.Count : 0;
        return total == 0 ? 0 : 100f * techs!.Count(tech => IsUnlocked(database, tech.ID)) / total;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
        if (!_dragging)
            return;
        _position += args.Relative;
        foreach (var child in DragContainer.Children)
            LayoutContainer.SetPosition(child, child.Position + args.Relative);
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);
        if (args.Delta.Y == 0)
            return;

        // Do not zoom the tech tree while the cursor is over the opened info panel.
        if (TechnologyInfoPanel.Visible && IsPointerOverPanel(args.GlobalPosition))
            return;

        var zoom = Math.Clamp(_zoom + (args.Delta.Y > 0 ? 0.125f : -0.125f), 0.5f, 2f);
        if (MathHelper.CloseTo(zoom, _zoom))
            return;

        var cursor = args.GlobalPosition - DragContainer.GlobalPosition;
        _position = cursor - (cursor - _position) * zoom / _zoom;
        _zoom = zoom;
        RecenterItems();
        args.Handle();
    }

    private bool IsPointerOverPanel(Vector2 globalPosition)
    {
        var local = globalPosition - TechnologyInfoPanel.GlobalPosition;
        return local.X >= 0 &&
               local.Y >= 0 &&
               local.X <= TechnologyInfoPanel.Width &&
               local.Y <= TechnologyInfoPanel.Height;
    }

    private void OnDragKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _dragging = true;
    }

    private void OnDragKeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _dragging = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => _dragging ? DragMode.None : base.GetDragModeFor(relativeMousePos);

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text.Trim().ToLowerInvariant();
        _currentMatch = -1;
        UpdateMatches();
        UpdateTree();
    }

    private void OnSearchEntered(LineEdit.LineEditEventArgs args)
    {
        if (_matches.Count == 0)
            return;
        _currentMatch = (_currentMatch + 1) % _matches.Count;
        var match = _matches[_currentMatch];
        if (_selectedDiscipline != match.Tech.Discipline.Id)
        {
            _selectedDiscipline = match.Tech.Discipline.Id;
            if (_disciplineTabs.TryGetValue(_selectedDiscipline, out var tab))
                tab.Pressed = true;
            UpdateTree();
        }
        SelectTech(match.Tech, match.Availability);
        CenterOn(match.Tech);
    }

    private void UpdateMatches()
    {
        _matches.Clear();
        _matchIds.Clear();
        if (_searchText.Length == 0)
            return;

        foreach (var tech in _technologiesByDiscipline.Values.SelectMany(x => x))
        {
            if (!MatchesSearch(tech))
                continue;
            _matches.Add((tech, List[tech.ID]));
            _matchIds.Add(tech.ID);
        }
        _matches.Sort((a, b) => string.Compare(a.Tech.ID, b.Tech.ID, StringComparison.Ordinal));
    }

    private bool MatchesSearch(TechnologyPrototype tech)
    {
        if (Loc.GetString(tech.Name).Contains(_searchText, StringComparison.OrdinalIgnoreCase))
            return true;
        foreach (var id in tech.RecipeUnlocks)
        {
            var recipe = _prototype.Index<LatheRecipePrototype>(id);
            if (recipe.Name is { } name && Loc.GetString(name).Contains(_searchText, StringComparison.OrdinalIgnoreCase))
                return true;
            if (recipe.Result is { } result && Loc.GetString(_prototype.Index(result).Name).Contains(_searchText, StringComparison.OrdinalIgnoreCase))
                return true;
        }
        return false;
    }

    public void SelectTech(TechnologyPrototype tech, ResearchAvailability availability)
    {
        CurrentTech = tech.ID;
        ShowInfo(tech, availability);
    }

    public void UpdateNetworkLogs(List<ResearchNetworkLogEntry> logs)
    {
        _networkLogs = logs;
        _networkLogWindow?.SetLogs(logs);
    }

    private void OpenNetworkLog()
    {
        _networkLogWindow?.Close();
        _networkLogWindow = new FancyResearchConsoleNetworkLogWindow();
        _networkLogWindow.OnClose += () => _networkLogWindow = null;
        _networkLogWindow.SetLogs(_networkLogs);
        _networkLogWindow.OpenCentered();
    }

    private bool HasAccess()
    {
        return _player.LocalEntity is not { } local ||
               !_entity.TryGetComponent(Entity, out AccessReaderComponent? reader) ||
               _accessReader.IsAllowed(local, Entity, reader);
    }

    private void ShowInfo(TechnologyPrototype tech, ResearchAvailability availability)
    {
        TechnologyInfoPanel.Visible = true;
        if (InfoContainer.Children.FirstOrDefault() is FancyTechnologyInfoPanel current && current.Prototype == tech)
        {
            current.UpdateAvailability(HasAccess(), availability);
            if (_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? currentDatabase))
                current.UpdateItemRequirements(currentDatabase, _sprite);
            return;
        }

        InfoContainer.RemoveAllChildren();
        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        var panel = new FancyTechnologyInfoPanel(tech, HasAccess(), availability, database, _sprite);
        panel.BuyAction += bought =>
        {
            if (HasAccess() && List.GetValueOrDefault(bought.ID) == ResearchAvailability.Available)
                OnTechnologyCardPressed?.Invoke(bought.ID);
        };
        InfoContainer.AddChild(panel);
    }

    private void CloseInfo()
    {
        CurrentTech = null;
        InfoContainer.RemoveAllChildren();
        TechnologyInfoPanel.Visible = false;
    }

    private static bool IsUnlocked(TechnologyDatabaseComponent database, string technology)
    {
        foreach (var unlocked in database.UnlockedTechnologies)
        {
            if (unlocked == technology)
                return true;
        }

        return false;
    }

    public void Recenter()
    {
        if (_items.Count == 0 || DragContainer.Size == Vector2.Zero)
            return;

        var min = new Vector2(_items.Min(item => item.TreePosition.X), _items.Min(item => item.TreePosition.Y));
        var max = new Vector2(_items.Max(item => item.TreePosition.X), _items.Max(item => item.TreePosition.Y));
        _position = DragContainer.Size / 2f - (min + max) / 2f * _zoom;
        RecenterItems();
        _initialTreePositionSet = true;
    }

    private void OnDragContainerResized()
    {
        if (_initialTreePositionSet || _items.Count == 0 || DragContainer.Size == Vector2.Zero)
            return;

        Recenter();
    }

    private void CenterOn(TechnologyPrototype tech)
    {
        var item = _items.FirstOrDefault(item => item.Prototype == tech);
        if (item == null)
            return;

        _position = DragContainer.Size / 2f - item.TreePosition * _zoom;
        RecenterItems();
    }

    private void ClearItems()
    {
        foreach (var item in _items)
            DragContainer.RemoveChild(item);
        _items.Clear();
        DragContainer.InvalidateMeasure();
    }

    private void RecenterItems()
    {
        foreach (var item in _items)
        {
            item.SetScale(_zoom);
            LayoutContainer.SetPosition(item, _position + item.TreePosition * _zoom);
        }
    }

    public override void Close()
    {
        RecipeSearchLineEdit.OnTextChanged -= OnSearchChanged;
        RecipeSearchLineEdit.OnTextEntered -= OnSearchEntered;
        DragContainer.OnResized -= OnDragContainerResized;
        _networkLogWindow?.Close();
        base.Close();
    }
}
