using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleNetworkLogWindow : FancyWindow
{
    private List<ResearchNetworkLogEntry> _entries = new();

    public FancyResearchConsoleNetworkLogWindow()
    {
        RobustXamlLoader.Load(this);
        SearchInput.OnTextChanged += _ => RefreshLogs();
    }

    public void SetLogs(List<ResearchNetworkLogEntry> entries)
    {
        _entries = entries;
        RefreshLogs();
    }

    private void RefreshLogs()
    {
        var search = SearchInput.Text.Trim();
        var message = new FormattedMessage();
        var count = 0;
        for (var i = _entries.Count - 1; i >= 0; i--)
        {
            var entry = _entries[i];
            if (search.Length > 0 && !entry.Message.Contains(search, StringComparison.OrdinalIgnoreCase))
                continue;
            message.AddMarkupOrThrow($"[color=#8FA6C9]{entry.Timestamp:hh\\:mm\\:ss}[/color] {FormattedMessage.EscapeText(entry.Message)}\n");
            count++;
        }

        if (count == 0)
            message.AddText(Loc.GetString("research-network-log-empty"));
        LogsLabel.SetMessage(message);
    }
}
