using Content.Client.Lathe;
using Content.Client.Research;
using Content.Client.Research.UI;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyTechnologyInfoPanel : Control
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    public readonly TechnologyPrototype Prototype;
    public event Action<TechnologyPrototype>? BuyAction;

    // Persisted alternative selections of item requirements, surviving UI refreshes.
    private readonly Dictionary<int, int> _requirementSelections = new();

    public FancyTechnologyInfoPanel(
        TechnologyPrototype proto,
        bool hasAccess,
        ResearchAvailability availability,
        TechnologyDatabaseComponent database,
        SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Prototype = proto;

        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        DisciplineTexture.Texture = sprite.Frame0(_prototype.Index<TechDisciplinePrototype>(proto.Discipline).Icon);
        TechnologyTexture.Texture = sprite.Frame0(proto.Icon);
        InitializePrerequisites(proto, _entity.System<ResearchSystem>(), sprite);
        UpdateItemRequirements(database, sprite);
        InitializeRecipeUnlocks(proto, _entity.System<LatheSystem>(), sprite);

        UpdateAvailability(hasAccess, availability);
        ResearchButton.OnPressed += Bought;
    }

    public void UpdateAvailability(bool hasAccess, ResearchAvailability availability)
    {
        ResearchButton.ToolTip = hasAccess ? null : Loc.GetString("research-console-no-access-popup");
        ResearchButton.Text = Loc.GetString(availability == ResearchAvailability.Researched
            ? "research-console-menu-server-researched-button"
            : "research-console-menu-server-research-button");
        var color = availability switch
        {
            ResearchAvailability.Researched => Color.LimeGreen,
            ResearchAvailability.PrereqsMet or ResearchAvailability.Unavailable => Color.Crimson,
            _ => (Color?) null
        };
        TechnologyCostLabel.SetMessage(
            FormattedMessage.FromMarkupOrThrow(Loc.GetString("research-console-tech-cost-label",
                ("amount", ResearchPointUiHelpers.BuildCostMarkup(
                    Prototype,
                    _entity.System<ResearchSystem>(),
                    _prototype)))),
            defaultColor: color);
        ResearchButton.Disabled = !hasAccess || availability != ResearchAvailability.Available;
    }

    private void InitializePrerequisites(TechnologyPrototype proto, ResearchSystem research, SpriteSystem sprite)
    {
        NoPrereqLabel.Visible = proto.TechnologyPrerequisites.Count == 0;
        PrereqsContainer.Visible = !NoPrereqLabel.Visible;
        foreach (var id in proto.TechnologyPrerequisites)
        {
            var tech = _prototype.Index<TechnologyPrototype>(id);
            RequiredTechContainer.AddChild(new MiniTechnologyCardControl(
                tech,
                _prototype,
                sprite,
                research.GetTechnologyDescription(tech, true, false, true)));
        }
    }

    private void InitializeRecipeUnlocks(TechnologyPrototype proto, LatheSystem lathe, SpriteSystem sprite)
    {
        foreach (var id in proto.RecipeUnlocks)
            UnlocksContainer.AddChild(new MiniRecipeCardControl(proto, _prototype.Index<LatheRecipePrototype>(id), _prototype, sprite, lathe));

        foreach (var generic in proto.GenericUnlocks)
            UnlocksContainer.AddChild(new Label { Text = Loc.GetString(generic.UnlockDescription) });
    }

    public void UpdateItemRequirements(TechnologyDatabaseComponent database, SpriteSystem sprite)
    {
        ItemRequirementsList.RemoveAllChildren();
        ItemRequirementsContainer.Visible = Prototype.ResearchRequirements.Count > 0;
        IReadOnlyDictionary<ProtoId<TechnologyPrototype>, Dictionary<int, int>> progress = database.CompletedResearchRequirements;
        progress.TryGetValue(Prototype.ID, out var completed);
        for (var i = 0; i < Prototype.ResearchRequirements.Count; i++)
        {
            var index = i;
            ItemRequirementsList.AddChild(new ResearchItemRequirementControl(
                Prototype.ResearchRequirements[i],
                completed?.GetValueOrDefault(index) ?? 0,
                _requirementSelections.GetValueOrDefault(index),
                selected => _requirementSelections[index] = selected,
                _prototype,
                sprite));
        }
    }

    private void Bought(BaseButton.ButtonEventArgs args) => BuyAction?.Invoke(Prototype);

    protected override void ExitedTree()
    {
        ResearchButton.OnPressed -= Bought;
        base.ExitedTree();
    }
}
