using Content.Client.Lathe;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class MiniRecipeCardControl : Control
{
    public MiniRecipeCardControl(TechnologyPrototype technology, LatheRecipePrototype recipe, IPrototypeManager prototypes, SpriteSystem sprite, LatheSystem lathe)
    {
        RobustXamlLoader.Load(this);
        Background.ModulateSelfOverride = prototypes.Index<TechDisciplinePrototype>(technology.Discipline).Color;
        NameLabel.SetMessage(lathe.GetRecipeName(recipe));

        if (recipe.Result is { } result)
            Showcase.Texture = sprite.Frame0(prototypes.Index(result));
        else if (recipe.Icon is { } icon)
            Showcase.Texture = sprite.Frame0(icon);

        if (recipe.Description.HasValue)
        {
            var tooltip = new Tooltip();
            tooltip.SetMessage(FormattedMessage.FromUnformatted(lathe.GetRecipeDescription(recipe)));
            Main.TooltipSupplier = _ => tooltip;
        }
    }
}
