using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchServerNetworkWindow : FancyWindow
{
    public event Action<string>? OnApply;

    public ResearchServerNetworkWindow(int id, string name, string networkId)
    {
        RobustXamlLoader.Load(this);
        ServerLabel.Text = Loc.GetString("research-server-network-server", ("id", id), ("name", name));
        NetworkIdInput.Text = networkId;
        ApplyButton.OnPressed += _ => Apply();
        NetworkIdInput.OnTextEntered += _ => Apply();
    }

    private void Apply()
    {
        OnApply?.Invoke(NetworkIdInput.Text);
        Close();
    }
}
