// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchExperimentScannerMenu : FancyWindow
{
    private readonly List<(RichTextLabel Label, Control Container, float Inset)> _wrappingLabels = new();

    public event Action? ServerPressed;

    public ResearchExperimentScannerMenu()
    {
        RobustXamlLoader.Load(this);
        ServerButton.OnPressed += _ => ServerPressed?.Invoke();

        RegisterWrap(LastResult, LogContainer);
    }

    private void RegisterWrap(RichTextLabel label, Control container, float inset = 2f)
    {
        label.HorizontalExpand = true;
        label.HorizontalAlignment = HAlignment.Stretch;
        _wrappingLabels.Add((label, container, inset));
        container.OnResized += UpdateWrapping;
    }

    private void UpdateWrapping()
    {
        foreach (var (label, container, inset) in _wrappingLabels)
        {
            var width = container.Size.X - inset;
            if (width <= 8f)
                continue;

            if (!MathHelper.CloseTo(label.SetWidth, width))
                label.SetWidth = width;
        }
    }

    public void UpdateState(ResearchExperimentScannerState state)
    {
        ServerLabel.Text = state.ServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", state.ServerName));
        ResearchExperimentUiHelpers.Fill(Experiments, state.Experiments);
        ResearchExperimentUiHelpers.SetResult(LastResult, state.LastResult);
        UpdateWrapping();
    }
}
