using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Research;
using Content.Shared._Onyx.Research.Prototypes;
using Content.Shared.Research.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchServerControlWindow : FancyWindow
{
    public event Action<int>? OnToggleGeneration;
    public event Action<int, string>? OnSetNetwork;
    private List<ResearchNetworkLogEntry> _logs = new();

    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;

    private readonly SharedResearchSystem _research = default!;

    public ResearchServerControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _ent.System<SharedResearchSystem>();
        LogSearchInput.OnTextChanged += _ => RefreshLogs();
    }

    public void UpdateState(ResearchServerControlBoundInterfaceState state)
    {
        ServerEntries.RemoveAllChildren();
        string? network = null;
        foreach (var server in state.Servers)
        {
            if (network != server.NetworkId)
            {
                network = server.NetworkId;
                ServerEntries.AddChild(new Label
                {
                    Text = Loc.GetString("research-server-control-network", ("network", network)),
                    StyleClasses = { "LabelHeading" },
                });
            }

            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#23232A"),
                    BorderColor = server.Authority ? Color.FromHex("#6A9F68") : Color.FromHex("#4A4A56"),
                    BorderThickness = new Thickness(1),
                },
            };
            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(8),
                SeparationOverride = 3,
            };
            content.AddChild(new Label
            {
                Text = Loc.GetString("research-server-control-server-name", ("id", server.Id), ("name", server.Name)),
            });
            content.AddChild(new Label
            {
                Text = Loc.GetString(server.Authority
                        ? "research-server-control-authority"
                        : "research-server-control-forwarded",
                    ("authorityId", server.AuthorityId)),
                Modulate = server.Authority ? Color.LightGreen : Color.LightGray,
            });
            content.AddChild(new Label
            {
                Text = Loc.GetString("research-server-control-telemetry",
                    ("power", Loc.GetString(server.Powered ? "research-server-control-powered" : "research-server-control-unpowered"))),
            });
            var table = BuildPointsTable(server);
            if (table != null)
                content.AddChild(table);
            var toggle = new Button
            {
                Text = Loc.GetString(server.GenerationEnabled
                    ? "research-server-control-disable-generation"
                    : "research-server-control-enable-generation"),
                HorizontalExpand = true,
            };
            var id = server.Id;
            toggle.OnPressed += _ => OnToggleGeneration?.Invoke(id);
            content.AddChild(toggle);
            var configure = new Button
            {
                Text = Loc.GetString("research-server-control-configure-network"),
                HorizontalExpand = true,
            };
            configure.OnPressed += _ => OpenNetworkEditor(server);
            content.AddChild(configure);
            panel.AddChild(content);
            ServerEntries.AddChild(panel);
        }

        if (state.Servers.Count == 0)
            ServerEntries.AddChild(new Label { Text = Loc.GetString("research-server-control-empty") });

        _logs = state.Logs;
        RefreshLogs();
    }

    private void OpenNetworkEditor(ResearchServerControlEntry server)
    {
        var editor = new ResearchServerNetworkWindow(server.Id, server.Name, server.NetworkId);
        editor.OnApply += networkId => OnSetNetwork?.Invoke(server.Id, networkId);
        editor.OpenCentered();
    }

    /// <summary>
    /// Builds a per-point-type table (type | generation | network balance) for a server.
    /// </summary>
    private GridContainer? BuildPointsTable(ResearchServerControlEntry server)
    {
        var types = new List<string>();
        foreach (var balance in server.NetworkBalances)
        {
            if (!types.Contains(balance.Type))
                types.Add(balance.Type);
        }
        foreach (var generation in server.Generation)
        {
            if (!types.Contains(generation.Type))
                types.Add(generation.Type);
        }

        if (types.Count == 0)
            return null;

        var grid = new GridContainer
        {
            Columns = 3,
            HorizontalExpand = true,
        };

        grid.AddChild(MakeTableHeader(Loc.GetString("research-server-control-table-type")));
        grid.AddChild(MakeTableHeader(Loc.GetString("research-server-control-table-generation")));
        grid.AddChild(MakeTableHeader(Loc.GetString("research-server-control-table-balance")));

        foreach (var type in types)
        {
            var generation = SharedResearchSystem.GetPointAmount(server.Generation, type);
            var balance = SharedResearchSystem.GetPointAmount(server.NetworkBalances, type);
            var color = _prototypes.TryIndex<ResearchPointTypePrototype>(type, out var prototype)
                ? prototype.Color
                : Color.White;

            grid.AddChild(new Label
            {
                Text = _research.GetPointTypeName(type),
                Modulate = color,
                Margin = new Thickness(0, 0, 12, 0),
            });
            grid.AddChild(new Label
            {
                Text = Loc.GetString("research-server-control-table-generation-value", ("value", generation)),
                Margin = new Thickness(0, 0, 12, 0),
            });
            grid.AddChild(new Label { Text = balance.ToString() });
        }

        return grid;
    }

    private Label MakeTableHeader(string text)
    {
        return new Label
        {
            Text = text,
            Modulate = Color.Gray,
            Margin = new Thickness(0, 0, 12, 2),
        };
    }

    private void RefreshLogs()
    {
        var search = LogSearchInput.Text.Trim();
        var message = new FormattedMessage();
        var count = 0;
        foreach (var entry in _logs)
        {
            if (search.Length > 0 && !entry.Message.Contains(search, StringComparison.OrdinalIgnoreCase))
                continue;
            message.AddMarkupOrThrow($"[color=#8FA6C9]{entry.Timestamp:hh\\:mm\\:ss}[/color] {FormattedMessage.EscapeText(entry.Message)}\n");
            count++;
        }

        if (count == 0)
            message.AddText(Loc.GetString("research-network-log-empty"));
        LogsLabel.SetMessage(message);
    }
}
