// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchExperimentMachineMenu : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly ResearchSystem _research;
    private readonly List<(RichTextLabel Label, Control Container, float Inset)> _wrappingLabels = new();

    public event Action? ServerPressed;
    public event Action? RunPressed;

    public ResearchExperimentMachineMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entManager.System<ResearchSystem>();

        ServerButton.OnPressed += _ => ServerPressed?.Invoke();
        RunButton.OnPressed += _ => RunPressed?.Invoke();

        RegisterWrap(BalanceLabel, ServerContainer);
        RegisterWrap(HintLabel, WorkContainer);
        RegisterWrap(LastResult, LogContainer);
    }

    private void RegisterWrap(RichTextLabel label, Control container, float inset = 2f)
    {
        label.HorizontalExpand = true;
        label.HorizontalAlignment = HAlignment.Stretch;
        _wrappingLabels.Add((label, container, inset));
        container.OnResized += UpdateWrapping;
    }

    private void UpdateWrapping()
    {
        foreach (var (label, container, inset) in _wrappingLabels)
        {
            var width = container.Size.X - inset;
            if (width <= 8f)
                continue;

            if (!MathHelper.CloseTo(label.SetWidth, width))
                label.SetWidth = width;
        }
    }

    public void UpdateState(ResearchExperimentMachineBuiState state)
    {
        ServerLabel.Text = state.ServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", state.ServerName));

        BalanceLabel.SetMessage(state.Balances.Count > 0
            ? FormattedMessage.FromMarkupOrThrow(Loc.GetString(
                "research-console-menu-research-points-balances-text",
                ("balances", ResearchPointUiHelpers.BuildBalanceMarkup(state.Balances, _research, _prototype))))
            : FormattedMessage.Empty);

        var idleStatus = Loc.GetString("research-experiment-machine-status-idle");
        StatusLabel.Text = Loc.GetString("research-experiment-machine-status", ("status", state.Status));
        RunButton.Disabled = state.Status != idleStatus;

        ResearchExperimentUiHelpers.Fill(Experiments, state.Experiments);
        ResearchExperimentUiHelpers.SetResult(LastResult, state.LastResult);
        UpdateWrapping();
    }
}
