using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchServerControlWindow : FancyWindow
{
    public event Action<int>? OnToggleGeneration;
    public event Action<int, string>? OnSetNetwork;
    private List<ResearchNetworkLogEntry> _logs = new();

    public ResearchServerControlWindow()
    {
        RobustXamlLoader.Load(this);
        LogSearchInput.OnTextChanged += _ => RefreshLogs();
    }

    public void UpdateState(ResearchServerControlBoundInterfaceState state)
    {
        ServerEntries.RemoveAllChildren();
        string? network = null;
        foreach (var server in state.Servers)
        {
            if (network != server.NetworkId)
            {
                network = server.NetworkId;
                ServerEntries.AddChild(new Label
                {
                    Text = Loc.GetString("research-server-control-network", ("network", network)),
                    StyleClasses = { "LabelHeading" },
                });
            }

            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#23232A"),
                    BorderColor = server.Authority ? Color.FromHex("#6A9F68") : Color.FromHex("#4A4A56"),
                    BorderThickness = new Thickness(1),
                },
            };
            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(8),
                SeparationOverride = 3,
            };
            content.AddChild(new Label
            {
                Text = Loc.GetString("research-server-control-server-name", ("id", server.Id), ("name", server.Name)),
            });
            content.AddChild(new Label
            {
                Text = Loc.GetString(server.Authority
                        ? "research-server-control-authority"
                        : "research-server-control-forwarded",
                    ("authorityId", server.AuthorityId)),
                Modulate = server.Authority ? Color.LightGreen : Color.LightGray,
            });
            content.AddChild(new Label
            {
                Text = Loc.GetString("research-server-control-telemetry",
                    ("power", Loc.GetString(server.Powered ? "research-server-control-powered" : "research-server-control-unpowered")),
                    ("rate", server.PointsPerSecond),
                    ("points", server.NetworkPoints)),
            });
            var toggle = new Button
            {
                Text = Loc.GetString(server.GenerationEnabled
                    ? "research-server-control-disable-generation"
                    : "research-server-control-enable-generation"),
                HorizontalExpand = true,
            };
            var id = server.Id;
            toggle.OnPressed += _ => OnToggleGeneration?.Invoke(id);
            content.AddChild(toggle);
            var configure = new Button
            {
                Text = Loc.GetString("research-server-control-configure-network"),
                HorizontalExpand = true,
            };
            configure.OnPressed += _ => OpenNetworkEditor(server);
            content.AddChild(configure);
            panel.AddChild(content);
            ServerEntries.AddChild(panel);
        }

        if (state.Servers.Count == 0)
            ServerEntries.AddChild(new Label { Text = Loc.GetString("research-server-control-empty") });

        _logs = state.Logs;
        RefreshLogs();
    }

    private void OpenNetworkEditor(ResearchServerControlEntry server)
    {
        var editor = new ResearchServerNetworkWindow(server.Id, server.Name, server.NetworkId);
        editor.OnApply += networkId => OnSetNetwork?.Invoke(server.Id, networkId);
        editor.OpenCentered();
    }

    private void RefreshLogs()
    {
        var search = LogSearchInput.Text.Trim();
        var message = new FormattedMessage();
        var count = 0;
        foreach (var entry in _logs)
        {
            if (search.Length > 0 && !entry.Message.Contains(search, StringComparison.OrdinalIgnoreCase))
                continue;
            message.AddMarkupOrThrow($"[color=#8FA6C9]{entry.Timestamp:hh\\:mm\\:ss}[/color] {FormattedMessage.EscapeText(entry.Message)}\n");
            count++;
        }

        if (count == 0)
            message.AddText(Loc.GetString("research-network-log-empty"));
        LogsLabel.SetMessage(message);
    }
}
