using Content.Shared.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class PlayTimeEditorWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IClientConsoleHost _consoleHost = default!;

    private readonly List<(string Name, string Tracker)> _allRoles = new();

    public PlayTimeEditorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var job in _prototypeManager.EnumeratePrototypes<JobPrototype>())
            _allRoles.Add((job.LocalizedName, job.PlayTimeTracker));

        _allRoles.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));
        RefreshFilteredRoles(string.Empty);
        RefreshButtons();

        PlayerNameLine.OnTextChanged += _ => RefreshButtons();
        MinutesInput.OnTextChanged += _ => RefreshButtons();
        MinutesInput.OnTextChanged += _ => UpdateTimeButtonsLabels();
        PlayerList.OnSelectionChanged += player => PlayerNameLine.Text = player?.Username ?? string.Empty;
        RoleFilterInput.OnTextChanged += _ => RefreshFilteredRoles(RoleFilterInput.Text.Trim());
        AddHourButton.OnPressed += _ => AdjustMinutes(60);
        AddDayButton.OnPressed += _ => AdjustMinutes(1440);
        AddWeekButton.OnPressed += _ => AdjustMinutes(10080);
        AddMonthButton.OnPressed += _ => AdjustMinutes(43200);
        ApplyRoleButton.OnPressed += OnApplyRole;
        ApplyTotalButton.OnPressed += OnApplyTotal;
        RoleOption.OnItemSelected += args => RoleOption.SelectId(args.Id);
    }

    private void RefreshFilteredRoles(string filter)
    {
        RoleOption.Clear();

        foreach (var (name, tracker) in _allRoles)
        {
            if (!name.Contains(filter, StringComparison.CurrentCultureIgnoreCase))
                continue;

            var index = RoleOption.ItemCount;
            RoleOption.AddItem(name);
            RoleOption.SetItemMetadata(index, tracker);
        }

        if (RoleOption.ItemCount > 0)
            RoleOption.SelectId(0);

        RefreshButtons();
    }

    private void RefreshButtons()
    {
        var valid = !string.IsNullOrWhiteSpace(PlayerNameLine.Text)
                    && int.TryParse(MinutesInput.Text, out var minutes)
                    && minutes != 0;
        ApplyTotalButton.Disabled = !valid;
        ApplyRoleButton.Disabled = !valid || RoleOption.ItemCount == 0;
    }

    private void OnApplyRole(BaseButton.ButtonEventArgs _)
    {
        if (RoleOption.SelectedMetadata is not string tracker)
            return;

        _consoleHost.ExecuteCommand(
            $"playtime_addrole_as \"{CommandParsing.Escape(PlayerNameLine.Text.Trim())}\" \"{CommandParsing.Escape(tracker)}\" {MinutesInput.Text}");
    }

    private void OnApplyTotal(BaseButton.ButtonEventArgs _)
    {
        _consoleHost.ExecuteCommand(
            $"playtime_addoverall_as \"{CommandParsing.Escape(PlayerNameLine.Text.Trim())}\" {MinutesInput.Text}");
    }

    private void UpdateTimeButtonsLabels()
    {
        _ = int.TryParse(MinutesInput.Text, out var minutes);
        AddHourButton.Text = $"+1h ({minutes / 60})";
        AddDayButton.Text = $"+1d ({minutes / 1440})";
        AddWeekButton.Text = $"+1w ({minutes / 10080})";
        AddMonthButton.Text = $"+30d ({minutes / 43200})";
    }

    private void AdjustMinutes(int delta)
    {
        _ = int.TryParse(MinutesInput.Text, out var current);
        MinutesInput.Text = checked(current + delta).ToString();
    }
}
