// SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2024 Simon <63975668+Simyon264@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.IO;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.CustomLawboard;
using Content.Shared.FixedPoint;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Markdown;
using Robust.Shared.Utility;
using YamlDotNet.RepresentationModel;

namespace Content.Client._Onyx.CustomLawboard;

[GenerateTypedNameReferences]
public sealed partial class LawboardSiliconLawUi : FancyWindow
{
    private const long MaxImportBytes = 64 * 1024;

    [Dependency] private IFileDialogManager _dialogManager = default!;
    [Dependency] private ILocalizationManager _localization = default!;
    [Dependency] private ILogManager _logManager = default!;
    [Dependency] private ISerializationManager _serialization = default!;

    private readonly List<SiliconLaw> _laws = new();
    private readonly ISawmill _sawmill;

    public event Action<List<string>>? LawsSaved;

    public LawboardSiliconLawUi()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("custom-lawboard-ui");

        NewLawButton.OnPressed += _ => AddLaw();
        Save.OnPressed += _ => LawsSaved?.Invoke(CreatePayload());
        Import.OnPressed += _ => ImportLaws();
        Export.OnPressed += _ => ExportLaws();
    }

    public void SetLaws(IEnumerable<SiliconLaw> laws)
    {
        _laws.Clear();
        foreach (var law in laws.OrderBy(law => law.Order).Take(CustomLawboardComponent.MaxLaws))
        {
            _laws.Add(new SiliconLaw
            {
                LawString = ResolveLawText(law.LawString),
                Order = FixedPoint2.New(_laws.Count + 1)
            });
        }

        Rebuild();
    }

    private void AddLaw()
    {
        if (_laws.Count >= CustomLawboardComponent.MaxLaws)
            return;

        _laws.Add(new SiliconLaw
        {
            Order = FixedPoint2.New(_laws.Count + 1)
        });
        Rebuild();
    }

    private void DeleteLaw(SiliconLaw law)
    {
        _laws.Remove(law);
        Renumber();
        Rebuild();
    }

    private void MoveLaw(SiliconLaw law, int direction)
    {
        var index = _laws.IndexOf(law);
        var target = index + direction;
        if (index < 0 || target < 0 || target >= _laws.Count)
            return;

        (_laws[index], _laws[target]) = (_laws[target], _laws[index]);
        Renumber();
        Rebuild();
    }

    private void Renumber()
    {
        for (var i = 0; i < _laws.Count; i++)
            _laws[i].Order = FixedPoint2.New(i + 1);
    }

    private void Rebuild()
    {
        LawContainer.RemoveAllChildren();
        foreach (var law in _laws)
        {
            var control = new LawboardSiliconLawContainer();
            control.SetLaw(law, law.LawString);
            control.MoveLawUp += value => MoveLaw(value, -1);
            control.MoveLawDown += value => MoveLaw(value, 1);
            control.DeleteAction += DeleteLaw;
            LawContainer.AddChild(control);
        }

        NewLawButton.Disabled = _laws.Count >= CustomLawboardComponent.MaxLaws;
    }

    private List<string> CreatePayload()
    {
        return _laws
            .Take(CustomLawboardComponent.MaxLaws)
            .Select(law => law.LawString.Length <= CustomLawboardComponent.MaxLawLength
                ? law.LawString
                : law.LawString[..CustomLawboardComponent.MaxLawLength])
            .ToList();
    }

    private async void ExportLaws()
    {
        var file = await _dialogManager.SaveFile(new FileDialogFilters(new FileDialogFilters.Group("yml")));
        if (file == null)
            return;

        await using var stream = file.Value.fileStream;
        try
        {
            var lawset = new SiliconLawset
            {
                Laws = _laws.Select(law => law.ShallowClone()).ToList(),
                ObeysTo = string.Empty
            };
            var node = _serialization.WriteValue(lawset.GetType(), lawset);
            await using var writer = new StreamWriter(stream);
            node.Write(writer);
        }
        catch (Exception exception)
        {
            _sawmill.Error($"Error exporting custom lawboard: {exception}");
        }
    }

    private async void ImportLaws()
    {
        await using var file = await _dialogManager.OpenFile(
            new FileDialogFilters(new FileDialogFilters.Group("yml")),
            FileAccess.Read);
        if (file == null)
            return;

        try
        {
            if (!file.CanSeek || file.Length > MaxImportBytes)
                throw new InvalidDataException("Custom lawboard file exceeds size limit.");

            using var reader = new StreamReader(file, EncodingHelpers.UTF8);
            var yaml = new YamlStream();
            yaml.Load(reader);
            if (yaml.Documents.Count != 1)
                throw new InvalidDataException("Custom lawboard file must contain one YAML document.");

            var lawset = _serialization.Read<SiliconLawset>(
                yaml.Documents[0].RootNode.ToDataNode(),
                notNullableOverride: true);
            SetLaws(lawset.Laws);
        }
        catch (Exception exception)
        {
            _sawmill.Error($"Error importing custom lawboard: {exception}");
        }
    }

    private string ResolveLawText(string text)
    {
        return _localization.TryGetString(text, out var localized) ? localized : text;
    }
}
