// SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2024 Simon <63975668+Simyon264@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.CustomLawboard;

[GenerateTypedNameReferences]
public sealed partial class LawboardSiliconLawContainer : BoxContainer
{
    private SiliconLaw? _law;

    public event Action<SiliconLaw>? MoveLawUp;
    public event Action<SiliconLaw>? MoveLawDown;
    public event Action<SiliconLaw>? DeleteAction;

    public LawboardSiliconLawContainer()
    {
        RobustXamlLoader.Load(this);

        MoveUp.OnPressed += _ => Invoke(MoveLawUp);
        MoveDown.OnPressed += _ => Invoke(MoveLawDown);
        Delete.OnPressed += _ => Invoke(DeleteAction);
        LawContent.OnTextChanged += _ =>
        {
            if (_law != null)
                _law.LawString = Rope.Collapse(LawContent.TextRope);
        };
        LawContent.Placeholder = new Rope.Leaf(Loc.GetString("silicon-law-ui-placeholder"));
    }

    public void SetLaw(SiliconLaw law, string text)
    {
        _law = law;
        LawNumberLabel.Text = Loc.GetString("laws-ui-law-header", ("id", law.Order));
        LawContent.TextRope = new Rope.Leaf(text);
    }

    private void Invoke(Action<SiliconLaw>? action)
    {
        if (_law != null)
            action?.Invoke(_law);
    }
}
