using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Onyx.Administration.TimeTransfer;

[GenerateTypedNameReferences]
public sealed partial class TimeTransferEntry : BoxContainer
{
    public string PlaytimeTracker { get; }
    public string JobName { get; }
    public string Time => TimeEdit.Text ?? string.Empty;

    public TimeTransferEntry(JobPrototype job, SpriteSystem sprites, IPrototypeManager prototypes)
        : this(job.PlayTimeTracker.Id, job.LocalizedName)
    {
        if (prototypes.TryIndex<JobIconPrototype>(job.Icon, out var icon))
            JobIcon.Texture = sprites.Frame0(icon.Icon);
    }

    public TimeTransferEntry(string playtimeTracker, string name)
    {
        RobustXamlLoader.Load(this);
        PlaytimeTracker = playtimeTracker;
        JobName = name;
        JobLabel.Text = JobName;
    }

    public void UpdateGroupVisibility(bool grouped)
    {
        TimeLabel.Visible = !grouped;
        TimeEdit.Visible = !grouped;
        GroupCheckbox.Visible = grouped;
    }

    public bool InGroup() => GroupCheckbox.Pressed;
}
