using System.Linq;
using Content.Shared._Onyx.Administration.TimeTransfer;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.Administration.TimeTransfer;

[GenerateTypedNameReferences]
public sealed partial class TimeTransferPanel : DefaultWindow
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;
    private TimeSpan? _confirmUntil;

    public event Action<(string PlayerId, List<TimeTransferData> Data, bool Overwrite)>? TransferRequested;

    public TimeTransferPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        var sprites = _entities.System<SpriteSystem>();
        foreach (var job in _prototypes.EnumeratePrototypes<JobPrototype>().OrderBy(job => job.LocalizedName))
            JobContainer.AddChild(new TimeTransferEntry(job, sprites, _prototypes));
        AddTimeButton.OnButtonUp += _ => Transfer();
        SetTimeButton.OnButtonUp += _ => ConfirmSet();
        GroupCheckbox.OnPressed += _ => UpdateGroup();
        JobSearch.OnTextChanged += _ => UpdateSearch();
        UpdateGroup();
        UpdateWarning(" ", Color.LightGreen);
    }

    public void UpdatePermission(bool allowed)
    {
        AddTimeButton.Visible = allowed;
        SetTimeButton.Visible = allowed;
        UpdateWarning(allowed ? " " : Loc.GetString("time-transfer-panel-warning-no-perms"), allowed ? Color.LightGreen : Color.DarkRed);
    }

    public void UpdateWarning(string text, Color color)
    {
        WarningLabel.FontColorOverride = color;
        WarningLabel.Text = text;
    }

    private void Transfer(bool overwrite = false)
    {
        if (string.IsNullOrWhiteSpace(PlayerLine.Text))
        {
            UpdateWarning(Loc.GetString("time-transfer-panel-warning-no-player"), Color.DarkRed);
            return;
        }

        var data = new List<TimeTransferData>();
        if (GroupCheckbox.Pressed)
        {
            if (string.IsNullOrWhiteSpace(GroupTimeLine.Text))
            {
                UpdateWarning(Loc.GetString("time-transfer-panel-warning-group-no-time"), Color.DarkRed);
                return;
            }
            data.AddRange(JobContainer.Children.OfType<TimeTransferEntry>().Where(entry => entry.InGroup())
                .Select(entry => new TimeTransferData(entry.PlaytimeTracker, GroupTimeLine.Text)));
        }
        else
        {
            data.AddRange(JobContainer.Children.OfType<TimeTransferEntry>()
                .Where(entry => !string.IsNullOrWhiteSpace(entry.Time))
                .Select(entry => new TimeTransferData(entry.PlaytimeTracker, entry.Time)));
        }

        if (data.Count == 0)
        {
            UpdateWarning(Loc.GetString("time-transfer-panel-warning-no-job"), Color.DarkRed);
            return;
        }
        TransferRequested?.Invoke((PlayerLine.Text, data, overwrite));
        UpdateWarning(Loc.GetString("time-transfer-panel-warning-transfer-process"), Color.Gold);
    }

    private void UpdateGroup()
    {
        GroupTimeLine.Visible = GroupCheckbox.Pressed;
        foreach (var entry in JobContainer.Children.OfType<TimeTransferEntry>())
            entry.UpdateGroupVisibility(GroupCheckbox.Pressed);
    }

    private void UpdateSearch()
    {
        foreach (var entry in JobContainer.Children.OfType<TimeTransferEntry>())
            entry.Visible = entry.JobName.Contains(JobSearch.Text, StringComparison.OrdinalIgnoreCase);
    }

    private void ConfirmSet()
    {
        if (_confirmUntil == null)
        {
            _confirmUntil = _timing.CurTime + TimeSpan.FromSeconds(3);
            SetTimeButton.ModulateSelfOverride = Color.DarkRed;
            SetTimeButton.Text = Loc.GetString("time-transfer-panel-set-time-confirm");
            return;
        }
        Transfer(true);
        ResetSet();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_confirmUntil != null && _timing.CurTime > _confirmUntil)
            ResetSet();
    }

    private void ResetSet()
    {
        _confirmUntil = null;
        SetTimeButton.ModulateSelfOverride = null;
        SetTimeButton.Text = Loc.GetString("time-transfer-panel-set-time");
    }
}
