using Content.Client._Onyx.Discord;
using Content.Shared.CCVar;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class DiscordLinkWindow : DefaultWindow
{
    [Dependency] private IClipboardManager _clipboard = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private DiscordIdManager _discordIdManager = default!;
    [Dependency] private IUriOpener _uriOpener = default!;
    [Dependency] private IConfigurationManager _cfg = default!;

    private const string UnknownString = "UNKNOWN";
    private const string DefaultChannelLink = "https://discord.com";
    private string? _discordId;
    private string? _discordUsername;
    private string? _linkCode;
    private readonly string _channelLink;

    public DiscordLinkWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var channel = _cfg.GetCVar(CCVars.DiscordLinkChannel);
        _channelLink = string.IsNullOrWhiteSpace(channel) ? DefaultChannelLink : channel;

        CopyCodeButton.OnPressed += _ => _clipboard.SetText(_linkCode ?? UnknownString);
        OpenDiscordButton.OnPressed += _ => _uriOpener.OpenUri(_channelLink);
        CopyInstructionButton.OnPressed += _ => _clipboard.SetText(InstructionText.Text ?? string.Empty);
        UnlinkDiscordButton.OnPressed += _ => _discordIdManager.RequestUnlink();
        _discordIdManager.DiscordInfoUpdated += UpdateStatus;
        UpdateStatus();
    }

    protected override void Opened()
    {
        base.Opened();
        _discordIdManager.RequestDiscordInfo();
        UpdateStatus();
    }

    private void UpdateStatus()
    {
        _discordId = _discordIdManager.TryGetDiscordId(out var discordId) ? discordId : null;
        _discordUsername = _discordIdManager.TryGetDiscordUsername(out var username) ? username : null;
        _linkCode = _discordIdManager.TryGetLinkCode(out var code) ? code : null;

        if (_discordId != null)
        {
            var lines = new[]
            {
                Loc.GetString("ui-lobby-discord-link-success-line1"),
                Loc.GetString("ui-lobby-discord-link-success-line2", ("username", _discordUsername ?? UnknownString), ("discordId", _discordId)),
                Loc.GetString("ui-lobby-discord-link-success-line3", ("icName", _player.LocalSession?.Name ?? UnknownString))
            };
            var message = new FormattedMessage();
            message.AddMarkupOrThrow(string.Join("\n", lines));
            SuccessRichText.SetMessage(message);
            InstructionContainer.Visible = false;
            SuccessContainer.Visible = true;
            return;
        }

        var instructions = new[]
        {
            Loc.GetString("ui-lobby-discord-link-instructions-line1"),
            Loc.GetString("ui-lobby-discord-link-instructions-line2", ("code", _linkCode ?? UnknownString)),
            Loc.GetString("ui-lobby-discord-link-instructions-line3", ("ckey", _player.LocalSession?.Name ?? UnknownString)),
            Loc.GetString("ui-lobby-discord-link-instructions-line4", ("channelLink", _channelLink)),
            Loc.GetString("ui-lobby-discord-link-instructions-line5")
        };
        var instructionMessage = new FormattedMessage();
        instructionMessage.AddMarkupOrThrow(string.Join("\n", instructions));
        InstructionText.SetMessage(instructionMessage);
        InstructionContainer.Visible = true;
        SuccessContainer.Visible = false;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _discordIdManager.DiscordInfoUpdated -= UpdateStatus;
        base.Dispose(disposing);
    }
}
