using System.Linq;
using Content.Client.Guidebook;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;
using static Content.Client.Corvax.SponsorOnlyHelpers;

namespace Content.Client._Onyx.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    public event Action<ProtoId<SpeciesPrototype>>? ChooseAction;

    private readonly HumanoidCharacterProfile _profile;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceManager _resources;
    private readonly DocumentParsingManager _documentParser;
    private ProtoId<SpeciesPrototype> _currentSpecies;

    public SpeciesWindow(
        HumanoidCharacterProfile profile,
        IPrototypeManager prototypes,
        IResourceManager resources,
        DocumentParsingManager documentParser)
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("species-window-title");
        _profile = profile;
        _prototypes = prototypes;
        _resources = resources;
        _documentParser = documentParser;

        var species = prototypes.EnumeratePrototypes<SpeciesPrototype>()
            .Where(proto => proto.RoundStart)
            .OrderBy(proto => Loc.GetString(proto.Name), StringComparer.CurrentCultureIgnoreCase)
            .ToList();

        AddCategory(species, SpeciesCategory.Classic, "ui-species-category-classic");
        AddCategory(species, SpeciesCategory.Unusual, "ui-species-category-unusual");
        AddCategory(species, SpeciesCategory.Special, "ui-species-category-special");

        Select.OnPressed += _ => ChooseAction?.Invoke(_currentSpecies);
        SelectSpecies(profile.Species);
    }

    private void AddCategory(List<SpeciesPrototype> species, SpeciesCategory category, string labelKey)
    {
        var categorySpecies = species.Where(proto => proto.Category == category).ToList();
        if (categorySpecies.Count == 0)
            return;

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f),
        };
        header.AddChild(new Label
        {
            Text = Loc.GetString(labelKey),
            Margin = new Thickness(2f),
        });
        header.AddChild(new PanelContainer
        {
            StyleClasses = { StyleClass.LowDivider },
            MinHeight = 1f,
            Margin = new Thickness(2f, 2f, 2f, 4f),
        });
        SpeciesContainer.AddChild(header);

        foreach (var proto in categorySpecies)
        {
            var name = Loc.GetString(proto.Name);
            if (proto.SponsorOnly)
                name += GetSponsorOnlySuffix(proto.ID);

            var button = new SpeciesButton(proto.ID)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Text = name,
                Margin = new Thickness(5f),
            };
            button.OnToggled += _ => SelectSpecies(proto.ID);
            SpeciesContainer.AddChild(button);
        }
    }

    private void SelectSpecies(ProtoId<SpeciesPrototype> speciesId)
    {
        DetailInfoContainer.DisposeAllChildren();
        _currentSpecies = speciesId;

        foreach (var child in SpeciesContainer.Children)
        {
            if (child is SpeciesButton button)
                button.Pressed = button.Species == speciesId;
        }

        var species = _prototypes.Index(speciesId);
        var previewProfile = _profile.WithSpecies(speciesId);
        var skinStrategy = _prototypes.Index(species.SkinColoration).Strategy;
        previewProfile = previewProfile.WithCharacterAppearance(
            HumanoidCharacterAppearance.EnsureValid(
                previewProfile.Appearance.WithSkinColor(skinStrategy.ClosestSkinColor(_profile.Appearance.SkinColor)),
                speciesId,
                previewProfile.Sex,
                []));

        Mob.LoadPreview(previewProfile, showClothes: false);
        JobLoadout.LoadPreview(previewProfile);
        Select.Disabled = _profile.Species == speciesId;

        if (species.Description is not { } description || !_resources.ContentFileExists(description))
            return;

        using var file = _resources.ContentFileReadText(description);
        _documentParser.TryAddMarkup(DetailInfoContainer, file.ReadToEnd());
    }

    private sealed partial class SpeciesButton(ProtoId<SpeciesPrototype> species) : Button
    {
        public readonly ProtoId<SpeciesPrototype> Species = species;
    }
}
