using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Surgery.Augments;

[GenerateTypedNameReferences]
public sealed partial class AugmentToolPanelMenu : RadialMenu
{
    [Dependency] private EntityManager _entities = default!;

    public event Action<EntityUid?>? ToolSelected;

    public AugmentToolPanelMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetTools(IEnumerable<EntityUid> tools)
    {
        Main.Children.Clear();
        foreach (var entity in tools)
            AddButton(entity);
        AddButton(null);
    }

    private void AddButton(EntityUid? entity)
    {
        var button = new RadialMenuButtonWithSector { SetSize = new Vector2(64f, 64f) };
        if (entity is { } uid)
            button.AddChild(new SpriteView(uid, _entities) { Scale = new Vector2(3f, 3f) });
        Main.AddChild(button);
        button.OnButtonUp += _ =>
        {
            ToolSelected?.Invoke(entity);
            Close();
        };
    }
}
