using System.Numerics;
using Content.Client.Atmos.EntitySystems;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Atmos.Crystallizer;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Onyx.Atmos.Crystallizer;

[GenerateTypedNameReferences]
public sealed partial class CrystallizerWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private readonly AtmosphereSystem _atmosphere;
    public bool Active = true;
    private Button? _selectedButton;
    private string? _selectedButtonId;
    private readonly Button _nothingButton = new();
    private readonly Dictionary<Button, string?> _buttonToRecipeId = new();
    private GasMixture? _gasMixture;
    public event Action<string?>? OnRecipeSelected;
    public event Action<float>? OnGasInputChanged;

    private const float MinDeviationRate = 0.9f;
    private const float MaxDeviationRate = 1.1f;

    public CrystallizerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _atmosphere = IoCManager.Resolve<IEntityManager>().System<AtmosphereSystem>();
        LocalizeStaticText();
        InitializeRecipeButtons();
        GasInput.OnValueChanged += args => OnGasInputChanged?.Invoke(Math.Max(args.Value, 0f));
    }

    private void LocalizeStaticText()
    {
        ControlsHeaderLabel.Text = Loc.GetString("crystallizer-ui-controls");
        PowerLabel.Text = Loc.GetString("crystallizer-ui-power");
        RecipeLabel.Text = Loc.GetString("crystallizer-ui-recipe");
        GasInputLabel.Text = Loc.GetString("crystallizer-ui-gas-input");
        ProgressAndRequirementsHeaderLabel.Text = Loc.GetString("crystallizer-ui-progress-and-requirements");
        ProgressLabel.Text = Loc.GetString("crystallizer-ui-progress");
        TemperatureLabel.Text = Loc.GetString("crystallizer-ui-temperature");
        GasesLabel.Text = Loc.GetString("crystallizer-ui-gases");
        RecipeDetailsHeaderLabel.Text = Loc.GetString("crystallizer-ui-recipe");
        SelectRecipePromptLabel.Text = Loc.GetString("crystallizer-ui-select-recipe-prompt");
    }

    public void SetActive(bool active)
    {
        Active = active;
        ToggleStatusButton.Pressed = active;
    }

    public void SetGasMixture(GasMixture? mixture)
    {
        _gasMixture = mixture;
        if (_selectedButton is null)
            return;

        CrystallizerRecipePrototype? recipe = null;
        if (_selectedButtonId is not null && _prototypeManager.TryIndex<CrystallizerRecipePrototype>(_selectedButtonId, out var prototype))
            recipe = prototype;
        SelectRecipeButton(_selectedButton, recipe);
        SetTemperatureBar(mixture, recipe);
    }

    public void SetProgressBar(float progressBar)
    {
        var fill = Math.Clamp(progressBar / 100f, 0f, 1f);
        if (fill < 0.0001f)
        {
            ProgressBarPanel.MinSize = new Vector2(0, 20);
            return;
        }

        if (ProgressBarPanel.Parent?.Parent is PanelContainer parent)
            ProgressBarPanel.MinSize = new Vector2(parent.Size.X * fill, 20);
    }

    private void SetTemperatureBar(GasMixture? mixture, CrystallizerRecipePrototype? recipe)
    {
        if (recipe is null || mixture is null || mixture.TotalMoles <= 0)
        {
            TemperatureBarPanel.MinSize = new Vector2(0, 20);
            TemperatureBarPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.White };
            return;
        }

        var temperature = mixture.Temperature;
        var minimum = recipe.MinimumTemperature;
        var maximum = recipe.MaximumTemperature;
        var fill = Math.Clamp((temperature - minimum * MinDeviationRate) /
                              (maximum * MaxDeviationRate - minimum * MinDeviationRate), 0f, 1f);
        var median = (minimum + maximum) / 2f;
        var color = (temperature >= minimum * MinDeviationRate && temperature <= minimum) ||
                    temperature >= maximum
            ? Color.Red
            : temperature >= median * MinDeviationRate && temperature <= median * MaxDeviationRate
                ? Color.Green
                : Color.White;

        if (TemperatureBarPanel.Parent?.Parent is PanelContainer parent)
        {
            TemperatureBarPanel.MinSize = new Vector2((parent.Size.X - 2) * fill, 18);
            TemperatureBarPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        }
    }

    private void InitializeRecipeButtons()
    {
        RecipesContainer.Children.Clear();
        _buttonToRecipeId.Clear();
        _nothingButton.Text = Loc.GetString("crystallizer-ui-nothing");
        _nothingButton.HorizontalExpand = true;
        _nothingButton.OnPressed += _ =>
        {
            SelectRecipeButton(_nothingButton);
            OnRecipeSelected?.Invoke(null);
        };
        _buttonToRecipeId[_nothingButton] = null;
        RecipesContainer.AddChild(_nothingButton);

        foreach (var recipe in _prototypeManager.EnumeratePrototypes<CrystallizerRecipePrototype>())
        {
            var button = new Button { Text = Loc.GetString(recipe.Name), HorizontalExpand = true };
            button.OnPressed += _ =>
            {
                SelectRecipeButton(button, recipe);
                OnRecipeSelected?.Invoke(recipe.ID);
            };
            _buttonToRecipeId[button] = recipe.ID;
            RecipesContainer.AddChild(button);
        }

        SelectRecipeButton(_nothingButton);
    }

    public void SelectRecipeById(string? recipeId)
    {
        var button = _nothingButton;
        CrystallizerRecipePrototype? recipe = null;
        foreach (var (candidate, id) in _buttonToRecipeId)
        {
            if (id != recipeId)
                continue;
            button = candidate;
            if (recipeId is not null && _prototypeManager.TryIndex<CrystallizerRecipePrototype>(recipeId, out var prototype))
                recipe = prototype;
            break;
        }
        SelectRecipeButton(button, recipe);
    }

    private void SelectRecipeButton(Button button, CrystallizerRecipePrototype? recipe = null)
    {
        if (_selectedButton is not null)
            _selectedButton.Pressed = false;
        _selectedButton = button;
        _selectedButton.Pressed = true;
        _selectedButtonId = _buttonToRecipeId[button];
        RequirementsContainer.Children.Clear();
        GasList.Children.Clear();

        if (recipe is null)
        {
            RequirementsContainer.AddChild(new Label { Text = Loc.GetString("crystallizer-ui-select-recipe-prompt") });
            return;
        }

        RequirementsContainer.AddChild(new Label { Text = Loc.GetString("crystallizer-ui-temperature") });
        RequirementsContainer.AddChild(new Label { Text = Loc.GetString("crystallizer-ui-recipe-minimum", ("temp", recipe.MinimumTemperature)) });
        RequirementsContainer.AddChild(new Label { Text = Loc.GetString("crystallizer-ui-recipe-maximum", ("temp", recipe.MaximumTemperature)) });
        RequirementsContainer.AddChild(new Label { Text = Loc.GetString("crystallizer-ui-gases") });

        var row = 0;
        for (var gasIndex = 0; gasIndex < recipe.MinimumRequirements.Length && gasIndex < Atmospherics.TotalNumberOfGases; gasIndex++)
        {
            if (recipe.MinimumRequirements[gasIndex] <= 0)
                continue;
            var gasName = Loc.GetString(_atmosphere.GetGas((Gas) gasIndex).Name);
            RequirementsContainer.AddChild(new Label { Text = Loc.GetString("crystallizer-ui-gas-requirement", ("gas", gasName), ("moles", recipe.MinimumRequirements[gasIndex])) });
            AddGasRow(gasName, _gasMixture?.GetMoles(gasIndex) ?? 0f, row++);
        }

        RequirementsContainer.AddChild(new Label { Text = " " });
        RequirementsContainer.AddChild(new Label { Text = Loc.GetString(recipe.EnergyRelease > 0 ? "crystallizer-ui-reaction-exothermic" : "crystallizer-ui-reaction-endothermic") });
        SetTemperatureBar(_gasMixture, recipe);
    }

    private void AddGasRow(string gasName, float moles, int row)
    {
        var contents = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
        contents.AddChild(new Label { Text = gasName, Margin = new Thickness(5) });
        contents.AddChild(new Control { HorizontalExpand = true });
        contents.AddChild(new Label { Text = Loc.GetString("crystallizer-ui-moles", ("moles", $"{moles:F2}")), Margin = new Thickness(5) });
        var panel = new PanelContainer { HorizontalExpand = true, Children = { contents } };
        panel.PanelOverride = new StyleBoxFlat { BackgroundColor = row % 2 == 0 ? Color.FromHex("#1B1B1E") : Color.FromHex("#2F2F38") };
        GasList.AddChild(panel);
    }
}
