using System.Linq;
using Content.Shared._Onyx.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Onyx.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : DefaultWindow
{
    private readonly LanguageSystem _languages;
    private readonly IPrototypeManager _prototypes;

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        _languages = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<LanguageSystem>();
        _prototypes = IoCManager.Resolve<IPrototypeManager>();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _languages.LanguagesChanged += UpdateState;
    }

    protected override void ExitedTree()
    {
        _languages.LanguagesChanged -= UpdateState;
        base.ExitedTree();
    }

    protected override void Opened()
    {
        UpdateState();
    }

    private void UpdateState()
    {
        var speaker = _languages.GetLocalSpeaker();
        if (speaker == null)
            return;

        CurrentLanguageLabel.Text = Loc.GetString("language-menu-current-language",
            ("language", _prototypes.Index(speaker.CurrentLanguage).Name));
        OptionsList.RemoveAllChildren();

        foreach (var id in speaker.SpokenLanguages.OrderBy(id => _prototypes.Index(id).Name))
        {
            var language = _prototypes.Index(id);
            var button = new Button
            {
                Text = Loc.GetString("language-menu-select"),
                Disabled = id == speaker.CurrentLanguage,
            };
            button.OnPressed += _ => _languages.SelectLanguage(id);

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = language.Name, HorizontalExpand = true });
            row.AddChild(button);

            var entry = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            entry.AddChild(row);
            var description = new RichTextLabel();
            description.SetMessage(language.Description);
            entry.AddChild(description);

            var panel = new PanelContainer();
            panel.StyleClasses.Add("PdaBorderRect");
            panel.AddChild(entry);
            OptionsList.AddChild(panel);
        }
    }
}
