using Content.Client._Onyx.UserActions.Tabs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.UserActions;

[GenerateTypedNameReferences]
public sealed partial class UserActionsPanel : Control
{
    [Dependency] private ISharedPlayerManager _playerManager = default!;

    private EntityUid? _lastPlayer;
    private bool _initialized;

    public UserActionsPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TabContainer.SetTabTitle(StatusTabControl, Loc.GetString("user-action-control-tab-status"));
        TabContainer.SetTabTitle(EmotesTabControl, Loc.GetString("user-action-control-tab-emote"));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_initialized && _lastPlayer == _playerManager.LocalEntity)
            return;

        _initialized = true;
        _lastPlayer = _playerManager.LocalEntity;
        UpdateTabs();
    }

    private void UpdateTabs()
    {
        UpdateTab(StatusTabControl);
        UpdateTab(EmotesTabControl);
    }

    private void UpdateTab(BaseTabControl tab)
    {
        TabContainer.SetTabVisible(tab, tab.UpdateState());
    }
}
