using System.Linq;
using System.Numerics;
using Content.Shared.Chat;
using Content.Shared.Chat.Prototypes;
using Content.Shared.Speech;
using Content.Shared.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.UserActions.Tabs;

[GenerateTypedNameReferences]
public sealed partial class EmotesTabControl : BaseTabControl
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private ISharedPlayerManager _playerManager = default!;

    private readonly List<Button> _buttons = new();
    private float _lastListWidth;

    public EmotesTabControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public override bool UpdateState()
    {
        EmotesList.RemoveAllChildren();
        _buttons.Clear();

        if (_playerManager.LocalEntity is not { Valid: true } player)
            return false;

        var emotes = _prototypeManager.EnumeratePrototypes<EmotePrototype>()
            .Where(emote => IsEmoteAvailable(emote, player))
            .OrderBy(emote => emote.Category)
            .ThenBy(emote => emote.ID)
            .ToList();

        foreach (var emote in emotes)
            _buttons.Add(CreateEmoteButton(emote));

        RebuildRows();

        return emotes.Count > 0;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_buttons.Count == 0 || MathF.Abs(_lastListWidth - EmotesList.Width) < 1f)
            return;

        RebuildRows();
    }

    private void RebuildRows()
    {
        foreach (var button in _buttons)
            button.Orphan();

        EmotesList.RemoveAllChildren();
        _lastListWidth = EmotesList.Width;
        var columnWidth = (MathF.Max(_lastListWidth, 280f) - 4f) / 2f;
        BoxContainer? row = null;

        foreach (var button in _buttons)
        {
            button.Measure(Vector2Helpers.Infinity);
            if (button.DesiredSize.X > columnWidth)
            {
                row = null;
                EmotesList.AddChild(CreateRow(button));
                continue;
            }

            if (row == null)
            {
                row = CreateRow(button);
                EmotesList.AddChild(row);
            }
            else
            {
                row.AddChild(button);
                row = null;
            }
        }
    }

    private static BoxContainer CreateRow(Button button)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2,
            HorizontalExpand = true,
        };
        button.SizeFlagsStretchRatio = 1f;
        row.AddChild(button);
        return row;
    }

    private Button CreateEmoteButton(EmotePrototype emote)
    {
        var name = Loc.GetString(emote.Name);
        var button = new Button
        {
            HorizontalExpand = true,
            MinSize = new Vector2(0, 28),
            Margin = new Thickness(1),
            RectClipContent = true,
            ToolTip = name,
        };
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };
        content.AddChild(new TextureRect
        {
            Texture = emote.Icon.Frame0(),
            Stretch = TextureRect.StretchMode.Scale,
            MinSize = new Vector2(24, 24),
            MaxSize = new Vector2(24, 24),
            Margin = new Thickness(0, 0, 5, 0),
        });
        content.AddChild(new Label
        {
            Text = name,
            ClipText = true,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        });
        button.AddChild(content);
        button.OnPressed += _ => _entityManager.RaisePredictiveEvent(new PlayEmoteMessage(emote.ID));
        return button;
    }

    private bool IsEmoteAvailable(EmotePrototype emote, EntityUid player)
    {
        var whitelist = _entityManager.System<EntityWhitelistSystem>();

        if (emote.Category == EmoteCategory.Invalid || emote.ChatTriggers.Count == 0)
            return false;

        if (!whitelist.IsWhitelistPassOrNull(emote.Whitelist, player) ||
            whitelist.IsWhitelistPass(emote.Blacklist, player))
            return false;

        return emote.Available ||
               !_entityManager.TryGetComponent<SpeechComponent>(player, out var speech) ||
               speech.AllowedEmotes.Contains(emote.ID);
    }
}
