using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Silicons.Borgs.UI;

[GenerateTypedNameReferences]
public sealed partial class RemoteDevicesMenu : FancyWindow
{
    public event Action<RemoteDeviceActionEvent>? OnRemoteDeviceAction;

    public RemoteDevicesMenu() => RobustXamlLoader.Load(this);

    public void Update(RemoteDevicesBuiState state)
    {
        RemoteDevicesDisplayContainer.Children.Clear();
        foreach (var device in state.DeviceList)
        {
            var control = new RemoteDeviceDisplay(device.NetEntityUid, device.DisplayName);
            control.OnRemoteDeviceAction += action => OnRemoteDeviceAction?.Invoke(action);
            RemoteDevicesDisplayContainer.AddChild(control);
        }
    }
}
