using Content.Shared._Onyx.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Silicons.Borgs.UI;

[GenerateTypedNameReferences]
public sealed partial class RemoteDeviceDisplay : Control
{
    public event Action<RemoteDeviceActionEvent>? OnRemoteDeviceAction;

    public RemoteDeviceDisplay(NetEntity target, string displayName)
    {
        RobustXamlLoader.Load(this);
        DeviceName.SetMessage(displayName);
        MoveButton.OnPressed += _ => OnRemoteDeviceAction?.Invoke(new RemoteDeviceActionEvent(RemoteDeviceActionType.MoveToDevice, target));
        TakeControlButton.OnPressed += _ => OnRemoteDeviceAction?.Invoke(new RemoteDeviceActionEvent(RemoteDeviceActionType.TakeControl, target));
    }
}
