using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Surgery.Augments.NeuroInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Surgery.Augments.NeuroInterface;

[GenerateTypedNameReferences]
public sealed partial class NeuroInterfaceWindow : FancyWindow
{
    private static readonly Color Cyan = Color.FromHex("#9fb0c4");
    private static readonly Color Teal = Color.FromHex("#4f6074");
    private static readonly Color Active = Color.FromHex("#c6d4e5");
    private static readonly Color Muted = Color.FromHex("#687483");

    public event Action<NeuroInterfaceMode>? OnModeChanged;
    public event Action<NetEntity, bool>? OnEnabledChanged;
    public event Action<NetEntity, NeuroRoutingAction>? OnRoutingChanged;

    private readonly Dictionary<NeuroInterfaceMode, Button> _modeButtons = new();
    private readonly ButtonGroup _modeGroup = new(isNoneSetAllowed: false);
    private readonly ButtonGroup _tabGroup = new(isNoneSetAllowed: false);
    private NeuroInterfaceBuiState? _state;
    private Page _page;
    private NeuroInterfaceBodyRegion? _region;

    private enum Page : byte
    {
        Overview,
        Hardware,
        Augments,
    }

    public NeuroInterfaceWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyPanels();

        ConfigureTab(OverviewTab, Page.Overview);
        ConfigureTab(HardwareTab, Page.Hardware);
        ConfigureTab(AugmentsTab, Page.Augments);

        foreach (var mode in Enum.GetValues<NeuroInterfaceMode>())
        {
            var button = CreateButton(Loc.GetString($"neuro-interface-mode-{mode.ToString().ToLowerInvariant()}"), 180);
            button.Group = _modeGroup;
            button.HorizontalExpand = true;
            button.OnPressed += _ => OnModeChanged?.Invoke(mode);
            ModeButtons.AddChild(button);
            _modeButtons.Add(mode, button);
        }

        RegionFilter.AddItem(Loc.GetString("neuro-interface-region-all"), -1);
        foreach (var region in Enum.GetValues<NeuroInterfaceBodyRegion>())
            RegionFilter.AddItem(Loc.GetString(GetRegionKey(region)), (int) region);
        RegionFilter.SelectId(-1);
        RegionFilter.OnItemSelected += args =>
        {
            RegionFilter.SelectId(args.Id);
            _region = args.Id < 0 ? null : (NeuroInterfaceBodyRegion) args.Id;
            RebuildAugments();
        };
        SearchBar.OnTextChanged += _ => RebuildAugments();

        ModeHint.SetMessage(Loc.GetString("neuro-interface-mode-hint"));
        OverviewTab.Pressed = true;
        ShowPage(Page.Overview);
    }

    public void UpdateState(NeuroInterfaceBuiState state)
    {
        var rebuildAugments = _state == null || _state.RouterCapacity != state.RouterCapacity ||
            _state.RoutedCount != state.RoutedCount ||
            !EntriesEqual(_state.Entries, state.Entries);
        _state = state;
        ModeLabel.Text = Loc.GetString("neuro-interface-mode-short",
            ("mode", Loc.GetString($"neuro-interface-mode-{state.Mode.ToString().ToLowerInvariant()}")));
        BandwidthLabel.Text = Loc.GetString("neuro-interface-bandwidth-value", ("value", state.Bandwidth));
        DemandLabel.Text = Loc.GetString("neuro-interface-demand-value", ("value", state.Demand));
        ChannelsLabel.Text = Loc.GetString("neuro-interface-channels-value",
            ("current", state.Channels), ("max", state.ChannelCapacity));
        OverloadLabel.Text = Loc.GetString("neuro-interface-overload-value", ("value", state.Overload));
        ChannelOverloadLabel.Text = Loc.GetString("neuro-interface-channel-overload-value",
            ("value", state.ChannelOverload));
        OverclockDamageLabel.Text = Loc.GetString("neuro-interface-overclock-damage-value",
            ("value", MathF.Round(state.OverclockDamage, 2)));
        PowerBalanceLabel.Text = Loc.GetString("neuro-interface-power-balance",
            ("generation", MathF.Round(state.PowerGeneration, 1)),
            ("consumption", MathF.Round(state.PowerConsumption, 1)));
        PowerSourceList.Children.Clear();
        if (state.PowerSources.Count == 0)
            PowerSourceList.AddChild(MutedLabel("neuro-interface-power-sources-empty"));
        else
        {
            foreach (var source in state.PowerSources)
                PowerSourceList.AddChild(new Label { Text = Loc.GetString("neuro-interface-power-source-entry", ("source", source)) });
        }
        BatteryList.Children.Clear();
        if (state.Batteries.Count == 0)
            BatteryList.AddChild(MutedLabel("neuro-interface-batteries-empty"));
        else
        {
            foreach (var battery in state.Batteries)
            {
                var percent = battery.Capacity > 0f ? battery.Charge / battery.Capacity * 100f : 0f;
                var batteryPanel = new PanelContainer { PanelOverride = PanelStyle("#1d2631", Teal) };
                var batteryText = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(7, 4),
                };
                batteryText.AddChild(new Label
                {
                    Text = battery.Name,
                    FontColorOverride = Active,
                    ClipText = true,
                });
                batteryText.AddChild(new Label
                {
                    Text = Loc.GetString("neuro-interface-battery-values",
                        ("charge", MathF.Round(battery.Charge)),
                        ("capacity", MathF.Round(battery.Capacity)),
                        ("percent", MathF.Round(percent)),
                        ("rate", MathF.Round(battery.ChargeRate, 1))),
                    StyleClasses = { "font-small" },
                    FontColorOverride = Cyan,
                    MouseFilter = MouseFilterMode.Stop,
                    ToolTip = Loc.GetString("neuro-interface-tooltip-battery-values"),
                });
                batteryPanel.AddChild(batteryText);
                BatteryList.AddChild(batteryPanel);
            }
        }
        ChipLabel.Text = SlotText("neuro-interface-slot-chip", state.ChipName);
        ChipEffectLabel.Text = Loc.GetString("neuro-interface-chip-effect",
            ("bandwidth", state.ChipBandwidth), ("channels", state.ChipChannels));
        CacheLabel.Text = SlotText("neuro-interface-slot-cache", state.CacheName);
        CacheEffectLabel.Text = Loc.GetString("neuro-interface-cache-effect", ("channels", state.CacheChannels));
        RouterLabel.Text = SlotText("neuro-interface-slot-router", state.RouterName);
        RouterEffectLabel.Text = Loc.GetString(state.RouterCapacity > 0
                ? "neuro-interface-router-effect"
                : "neuro-interface-router-effect-missing",
            ("current", state.RoutedCount), ("capacity", state.RouterCapacity));

        ExtensionList.Children.Clear();
        if (state.Modules.Count == 0)
            ExtensionList.AddChild(MutedLabel("neuro-interface-extensions-empty"));
        else
        {
            foreach (var module in state.Modules)
                ExtensionList.AddChild(new Label { Text = Loc.GetString("neuro-interface-extension-entry", ("name", module)) });
        }

        if (_modeButtons.TryGetValue(state.Mode, out var selected))
            selected.Pressed = true;
        foreach (var button in _modeButtons.Values)
            StyleButton(button, button.Pressed);

        if (rebuildAugments)
            RebuildAugments();
    }

    private void ConfigureTab(Button button, Page page)
    {
        button.Group = _tabGroup;
        StyleTab(button, false);
        button.OnPressed += _ =>
        {
            ShowPage(page);
            StyleTabs();
        };
    }

    private void ShowPage(Page page)
    {
        _page = page;
        OverviewScreen.Visible = page == Page.Overview;
        HardwareScreen.Visible = page == Page.Hardware;
        AugmentsScreen.Visible = page == Page.Augments;
        ScreenTitle.Text = Loc.GetString(page switch
        {
            Page.Overview => "neuro-interface-nav-overview",
            Page.Hardware => "neuro-interface-nav-hardware",
            _ => "neuro-interface-nav-augments",
        });
        ScreenSubtitle.Text = Loc.GetString(page switch
        {
            Page.Overview => "neuro-interface-overview-subtitle",
            Page.Hardware => "neuro-interface-hardware-subtitle",
            _ => "neuro-interface-augments-subtitle",
        });
        if (page == Page.Augments)
            RebuildAugments();
    }

    private void RebuildAugments()
    {
        if (_state == null)
            return;

        EntryList.Children.Clear();
        var search = SearchBar.Text.Trim();
        var filtered = _state.Entries
            .Where(entry => _region == null || entry.Region == _region)
            .Where(entry => search.Length == 0 || entry.Name.Contains(search, StringComparison.OrdinalIgnoreCase))
            .ToList();
        var count = filtered.Count;
        AugmentCount.Text = Loc.GetString("neuro-interface-augment-count", ("count", count));

        var routed = filtered.Where(entry => entry.Routed).OrderBy(entry => entry.RoutingOrder).ToList();
        if (routed.Count > 0)
        {
            EntryList.AddChild(CreateHeader("neuro-interface-routing-header", routed.Count));
            foreach (var entry in routed)
                EntryList.AddChild(CreateEntry(entry));
        }

        foreach (var group in filtered.Where(entry => !entry.Routed).GroupBy(entry => entry.Region).OrderBy(group => group.Key))
        {
            EntryList.AddChild(CreateGroupHeader(group.Key, group.Count()));
            foreach (var entry in group)
                EntryList.AddChild(CreateEntry(entry));
        }

        if (count == 0)
            EntryList.AddChild(MutedLabel("neuro-interface-augments-empty"));
    }

    private Control CreateGroupHeader(NeuroInterfaceBodyRegion region, int count)
    {
        var text = Loc.GetString("neuro-interface-region-header",
            ("region", Loc.GetString(GetRegionKey(region))), ("count", count));
        return CreateHeader(text);
    }

    private Control CreateHeader(string key, int count) => CreateHeader(Loc.GetString(key, ("count", count)));

    private Control CreateHeader(string text)
    {
        var panel = new PanelContainer { PanelOverride = PanelStyle("#0b292d", Teal) };
        panel.AddChild(new Label
        {
            Text = text,
            Margin = new Thickness(8, 4),
            FontColorOverride = Active,
        });
        return panel;
    }

    private Control CreateEntry(NeuroInterfaceEntryData entry)
    {
        var routerCapacity = _state?.RouterCapacity ?? 0;
        var routedCount = _state?.RoutedCount ?? 0;
        var panel = new PanelContainer
        {
            PanelOverride = PanelStyle(entry.Enabled ? "#082024" : "#071416", entry.Enabled ? Teal : Muted),
        };
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            Margin = new Thickness(7, 5),
        };
        var status = new Label
        {
            Text = Loc.GetString(entry.Status),
            MinWidth = 132,
            VerticalAlignment = VAlignment.Center,
            FontColorOverride = entry.Efficiency > 0f ? Cyan : Muted,
            MouseFilter = MouseFilterMode.Stop,
        };
        status.ToolTip = Loc.GetString("neuro-interface-entry-tooltip",
            ("name", entry.Name),
            ("status", Loc.GetString(entry.Status)),
            ("demand", entry.Demand),
            ("power", entry.Power),
            ("efficiency", MathF.Round(entry.Efficiency * 100f)),
            ("routing", Loc.GetString(entry.Routed
                ? "neuro-interface-routing-position"
                : "neuro-interface-routing-auto", ("position", entry.RoutingOrder + 1))),
            ("behavior", Loc.GetString(entry.Scalable
                ? "neuro-interface-behavior-scalable"
                : "neuro-interface-behavior-binary")));

        var identity = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        identity.AddChild(new Label
        {
            Text = entry.Name,
            ClipText = true,
            FontColorOverride = entry.Enabled ? Active : Muted,
        });
        identity.AddChild(new Label
        {
            Text = Loc.GetString("neuro-interface-entry-brief",
                ("load", entry.Demand),
                ("efficiency", MathF.Round(entry.Efficiency * 100f)),
                ("behavior", Loc.GetString(entry.Scalable
                    ? "neuro-interface-behavior-scalable-short"
                    : "neuro-interface-behavior-binary-short"))),
            StyleClasses = { "font-small" },
            FontColorOverride = entry.Efficiency > 0f ? Cyan : Muted,
            MouseFilter = MouseFilterMode.Stop,
            ToolTip = Loc.GetString("neuro-interface-tooltip-entry-brief"),
        });

        var routing = new Label
        {
            Text = Loc.GetString(entry.Routed
                ? "neuro-interface-routing-position-short"
                : "neuro-interface-routing-auto-short", ("position", entry.RoutingOrder + 1)),
            MinWidth = 42,
            Align = Label.AlignMode.Center,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Stop,
            ToolTip = Loc.GetString("neuro-interface-tooltip-routing"),
        };
        var up = CreateButton("^", 30);
        up.ToolTip = Loc.GetString("neuro-interface-routing-up-tooltip");
        up.OnPressed += _ => OnRoutingChanged?.Invoke(entry.Entity, NeuroRoutingAction.MoveUp);
        up.Disabled = !entry.Routed || entry.RoutingOrder == 0;
        var down = CreateButton("v", 30);
        down.ToolTip = Loc.GetString("neuro-interface-routing-down-tooltip");
        down.OnPressed += _ => OnRoutingChanged?.Invoke(entry.Entity, NeuroRoutingAction.MoveDown);
        down.Disabled = !entry.Routed || entry.RoutingOrder >= routedCount - 1;
        var route = CreateButton(Loc.GetString(entry.Routed
            ? "neuro-interface-routing-remove"
            : "neuro-interface-routing-add"), 92);
        route.ToolTip = Loc.GetString(routerCapacity > 0
            ? "neuro-interface-routing-toggle-tooltip"
            : "neuro-interface-routing-router-required");
        route.Disabled = !entry.Routed && (routerCapacity <= 0 || routedCount >= routerCapacity);
        route.OnPressed += _ => OnRoutingChanged?.Invoke(entry.Entity,
            entry.Routed ? NeuroRoutingAction.Remove : NeuroRoutingAction.Add);
        var toggle = CreateButton(Loc.GetString(entry.Enabled
            ? "neuro-interface-button-disable"
            : "neuro-interface-button-enable"), 92);
        StyleButton(toggle, entry.Enabled);
        toggle.OnPressed += _ => OnEnabledChanged?.Invoke(entry.Entity, !entry.Enabled);

        row.AddChild(identity);
        row.AddChild(status);
        row.AddChild(routing);
        row.AddChild(up);
        row.AddChild(down);
        row.AddChild(route);
        row.AddChild(toggle);
        panel.AddChild(row);
        return panel;
    }

    private void ApplyPanels()
    {
        MainFrame.PanelOverride = PanelStyle("#12171e", Teal, 2);
        TabRail.PanelOverride = PanelStyle("#0d1117", Teal);
        ContentPanel.PanelOverride = PanelStyle("#171d25", Teal);
        Divider.PanelOverride = PanelStyle("#4f6074", Teal);
        BandwidthPanel.PanelOverride = PanelStyle("#1d2631", Teal);
        DemandPanel.PanelOverride = PanelStyle("#1d2631", Teal);
        OverloadPanel.PanelOverride = PanelStyle("#1d2631", Teal);
        ModePanel.PanelOverride = PanelStyle("#161e28", Teal);
        PowerPanel.PanelOverride = PanelStyle("#161e28", Teal);
        ComponentsPanel.PanelOverride = PanelStyle("#1d2631", Teal);
        ExtensionsPanel.PanelOverride = PanelStyle("#161e28", Teal);
    }

    private void StyleTabs()
    {
        StyleTab(OverviewTab, OverviewTab.Pressed);
        StyleTab(HardwareTab, HardwareTab.Pressed);
        StyleTab(AugmentsTab, AugmentsTab.Pressed);
    }

    private static void StyleTab(Button button, bool selected)
    {
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(selected ? "#17333d" : "#151c25"),
            BorderColor = selected ? Color.FromHex("#62c7d5") : Teal,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 5,
            ContentMarginRightOverride = 5,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
        };
        button.Label.FontColorOverride = selected ? Color.FromHex("#d8fbff") : Cyan;
        button.Label.Align = Label.AlignMode.Center;
    }

    private static Button CreateButton(string text, float minWidth)
    {
        var button = new Button
        {
            Text = text,
            MinWidth = minWidth,
            MinHeight = 30,
        };
        StyleButton(button, false);
        return button;
    }

    private static void StyleButton(Button button, bool selected)
    {
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(selected ? "#465d76" : "#354455"),
            BorderColor = selected ? Active : Color.FromHex("#71839a"),
            BorderThickness = new Thickness(selected ? 2 : 1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
        };
        button.Label.FontColorOverride = selected ? Active : Color.FromHex("#d0dae6");
    }

    private static Label MutedLabel(string key) => new()
    {
        Text = Loc.GetString(key),
        FontColorOverride = Muted,
        HorizontalAlignment = HAlignment.Center,
        Margin = new Thickness(0, 12),
    };

    private static string SlotText(string key, string? name) => Loc.GetString(
        key, ("name", name ?? Loc.GetString("neuro-interface-slot-empty")));

    private static string GetRegionKey(NeuroInterfaceBodyRegion region) =>
        $"neuro-interface-region-{region.ToString().ToLowerInvariant()}";

    private static bool EntriesEqual(List<NeuroInterfaceEntryData> left, List<NeuroInterfaceEntryData> right)
    {
        if (left.Count != right.Count)
            return false;

        var rightByEntity = right.ToDictionary(entry => entry.Entity);
        foreach (var a in left)
        {
            if (!rightByEntity.TryGetValue(a.Entity, out var b) ||
                a.Name != b.Name || a.Demand != b.Demand || a.Power != b.Power ||
                a.Enabled != b.Enabled || a.Routed != b.Routed || a.RoutingOrder != b.RoutingOrder ||
                a.Efficiency != b.Efficiency ||
                a.Status != b.Status || a.Scalable != b.Scalable || a.Region != b.Region)
                return false;
        }
        return true;
    }

    private static StyleBoxFlat PanelStyle(string background, Color border, int thickness = 1) => new()
    {
        BackgroundColor = Color.FromHex(background),
        BorderColor = border,
        BorderThickness = new Thickness(thickness),
    };
}
