using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Shuttles;
using Content.Shared._Onyx.Shuttles.Components;
using Content.Shared.Access.Systems;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Map;

namespace Content.Client._Onyx.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class DockingConsoleWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPlayerManager _player = default!;

    public event Action<MapId>? OnFTL;
    public event Action? OnShuttleCall;

    private readonly AccessReaderSystem _access;
    private readonly EntityUid _owner;
    private readonly StyleBoxFlat _ftlStyle = new(Color.LimeGreen);
    private FTLState _state;
    private int? _selected;
    private readonly List<MapId> _destinations = new();
    private StartEndTime _ftlTime;

    public DockingConsoleWindow(EntityUid owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _access = _entityManager.System<AccessReaderSystem>();
        _owner = owner;
        FTLBar.ForegroundStyleBoxOverride = _ftlStyle;

        if (!_entityManager.TryGetComponent<DockingConsoleComponent>(owner, out var component))
            return;

        Title = Loc.GetString(component.WindowTitle);
        ShuttleCallButton.OnPressed += _ => OnShuttleCall?.Invoke();
        Destinations.OnItemSelected += args =>
        {
            _selected = args.ItemIndex;
            UpdateButton();
        };
        Destinations.OnItemDeselected += _ =>
        {
            _selected = null;
            UpdateButton();
        };
        FTLButton.OnPressed += _ =>
        {
            if (_selected is { } index && index < _destinations.Count)
                OnFTL?.Invoke(_destinations[index]);
        };

        SetShuttleAvailable(component.HasShuttle);
    }

    public void UpdateState(DockingConsoleState state)
    {
        _state = state.FTLState;
        _ftlTime = state.FTLTime;
        SetShuttleAvailable(state.HasShuttle);

        if (!state.HasShuttle)
            return;

        MapFTLState.Text = Loc.GetString($"shuttle-console-ftl-state-{_state}");
        _ftlStyle.BackgroundColor = Color.FromHex(_state switch
        {
            FTLState.Available => "#80C71F",
            FTLState.Starting => "#169C9C",
            FTLState.Travelling => "#8932B8",
            FTLState.Arriving => "#F9801D",
            _ => "#B02E26"
        });

        _selected = null;
        _destinations.Clear();
        Destinations.Clear();
        foreach (var destination in state.Destinations)
        {
            _destinations.Add(destination.Map);
            Destinations.AddItem(destination.Name);
        }

        UpdateButton();
    }

    private void SetShuttleAvailable(bool available)
    {
        ShuttleCallButton.Disabled = available || !HasAccess();
        Destinations.Visible = available;
        FTLButton.Disabled = !available;

        if (available)
            return;

        MapFTLState.Text = Loc.GetString("docking-console-no-shuttle");
        MapFTLMessage.Text = Loc.GetString("docking-console-ftl-message-Unknown");
        _ftlStyle.BackgroundColor = Color.FromHex("#B02E26");
    }

    private void UpdateButton()
    {
        var state = !HasAccess()
            ? MiningFtlState.NoAccess
            : _selected == null
                ? MiningFtlState.NoSelection
                : _state switch
                {
                    FTLState.Available => MiningFtlState.Ready,
                    FTLState.Cooldown => MiningFtlState.RechargingFtl,
                    FTLState.Starting or FTLState.Travelling or FTLState.Arriving => MiningFtlState.InFtl,
                    _ => MiningFtlState.Unknown
                };

        FTLButton.Disabled = state != MiningFtlState.Ready;
        MapFTLMessage.Text = Loc.GetString($"docking-console-ftl-message-{state}");
    }

    private bool HasAccess()
    {
        return _player.LocalSession?.AttachedEntity is { } player && _access.IsAllowed(player, _owner);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var progress = _ftlTime.ProgressAt(_timing.CurTime);
        FTLBar.Value = float.IsFinite(progress) ? progress : 1;
    }

    private enum MiningFtlState
    {
        Unknown,
        Ready,
        NoSelection,
        NoAccess,
        InFtl,
        RechargingFtl
    }
}
