- type: entity
  abstract: true
  parent: BaseItem
  id: BaseAugment
  components:
  - type: Augment
  - type: AugmentModuleSlots
    slots:
    - id: augment-module-1
      name: augment-module-slot-name
      whitelist:
        components: [ AugmentModule ]
    - id: augment-module-2
      name: augment-module-slot-name
      whitelist:
        components: [ AugmentModule ]
  - type: Organ
  - type: MechanicalOrgan
  - type: Cybernetics
  - type: TransplantCompatibility
    profile: Cybernetic
  - type: SurgeryTool
    ignoreToggle: true
  - type: Item
    size: Huge
  - type: Tag
    tags: [ Augment ]

- type: entity
  abstract: true
  parent: BaseAction
  id: BaseAugmentAction
  components:
  - type: InstantAction
    event: !type:AugmentActionEvent
