using System.Linq;
using Content.Client.Message;
using Content.Shared._Onyx.Xenobiology.Bounties;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.Xenobiology.Bounties;

[GenerateTypedNameReferences]
public sealed partial class XenobiologyBountyEntry : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    public Action? OnFulfill;
    public Action? OnSkip;
    private TimeSpan _untilSkip;

    public XenobiologyBountyEntry(XenobiologyBountyData bounty, TimeSpan untilSkip)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _untilSkip = untilSkip;
        if (!_prototypes.TryIndex(bounty.Bounty, out var prototype))
            return;

        var items = prototype.Entries.Select(entry => Loc.GetString("bounty-console-manifest-entry",
            ("amount", entry.Amount), ("item", Loc.GetString(entry.Name))));
        Manifest.SetMarkup(Loc.GetString("bounty-console-manifest-label", ("item", string.Join(", ", items))));
        Reward.SetMarkup(Loc.GetString("xenobiology-console-reward-label", ("reward", prototype.PointsAwarded)));
        Identifier.SetMarkup(Loc.GetString("bounty-console-id-label", ("id", bounty.Id)));
        Fulfill.OnPressed += _ => OnFulfill?.Invoke();
        Skip.OnPressed += _ => OnSkip?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _untilSkip -= TimeSpan.FromSeconds(args.DeltaSeconds);
        Skip.Disabled = _untilSkip > TimeSpan.Zero;
        Skip.Label.Text = Skip.Disabled ? _untilSkip.ToString("mm\\:ss") : Loc.GetString("bounty-console-skip-button-text");
    }
}
