using System.Linq;
using Content.Client.Message;
using Content.Shared._Onyx.Xenobiology.Bounties;
using Content.Shared.Cargo;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Xenobiology.Bounties;

[GenerateTypedNameReferences]
public sealed partial class XenobiologyBountyHistoryEntry : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypes = default!;

    public XenobiologyBountyHistoryEntry(XenobiologyBountyHistoryData bounty)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        if (!_prototypes.TryIndex(bounty.Bounty, out var prototype))
            return;

        var items = prototype.Entries.Select(entry => Loc.GetString("bounty-console-manifest-entry",
            ("amount", entry.Amount), ("item", Loc.GetString(entry.Name))));
        Manifest.SetMarkup(Loc.GetString("bounty-console-manifest-label", ("item", string.Join(", ", items))));
        Reward.SetMarkup(Loc.GetString("xenobiology-console-reward-label", ("reward", prototype.PointsAwarded)));
        Identifier.SetMarkup(Loc.GetString("bounty-console-id-label", ("id", bounty.Id)));
        Timestamp.SetMarkup(bounty.Timestamp.ToString(@"hh\:mm\:ss"));
        Notice.SetMarkup(bounty.Result == CargoBountyHistoryData.BountyResult.Completed
            ? Loc.GetString("bounty-console-history-notice-completed-label")
            : Loc.GetString("bounty-console-history-notice-skipped-label",
                ("id", FormattedMessage.EscapeText(bounty.ActorName ?? string.Empty))));
    }
}
