using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Xenobiology.Bounties;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.Xenobiology.Bounties;

[GenerateTypedNameReferences]
public sealed partial class XenobiologyBountyMenu : FancyWindow
{
    public Action<string>? OnFulfill;
    public Action<string>? OnSkip;
    private TimeSpan _untilRefresh;

    public XenobiologyBountyMenu()
    {
        RobustXamlLoader.Load(this);
        Tabs.SetTabTitle(0, Loc.GetString("bounty-console-tab-available-label"));
        Tabs.SetTabTitle(1, Loc.GetString("bounty-console-tab-history-label"));
    }

    public void UpdateEntries(
        List<XenobiologyBountyData> bounties,
        List<XenobiologyBountyHistoryData> history,
        TimeSpan untilSkip,
        TimeSpan untilRefresh)
    {
        _untilRefresh = untilRefresh;
        Entries.Children.Clear();
        foreach (var bounty in bounties)
        {
            var entry = new XenobiologyBountyEntry(bounty, untilSkip);
            entry.OnFulfill += () => OnFulfill?.Invoke(bounty.Id);
            entry.OnSkip += () => OnSkip?.Invoke(bounty.Id);
            Entries.AddChild(entry);
        }
        Entries.AddChild(new Control { MinHeight = 10 });

        History.Children.Clear();
        NoHistory.Visible = history.Count == 0;
        for (var i = history.Count - 1; i >= 0; i--)
            History.AddChild(new XenobiologyBountyHistoryEntry(history[i]));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _untilRefresh -= TimeSpan.FromSeconds(args.DeltaSeconds);
        RefreshTimer.SetMarkup(Loc.GetString("xenobiology-console-refresh-label",
            ("time", (_untilRefresh > TimeSpan.Zero ? _untilRefresh : TimeSpan.Zero).ToString("mm\\:ss"))));
    }
}
