- type: playTimeTracker
  id: JobSurgeon

- type: jobIcon
  parent: JobIcon
  id: JobIconSurgeon
  icon:
    sprite: /Textures/Interface/Misc/job_icons.rsi
    state: Surgeon
  jobName: job-name-surgeon
