using Content.Shared._Onyx.Clothing.Modsuits.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Clothing.Modsuits;

[GenerateTypedNameReferences]
public sealed partial class ModSuitModuleControl : PanelContainer
{
    public Action? RemoveButtonPressed;

    public ModSuitModuleControl(EntityUid module, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);

        ModuleView.SetEntity(module);
        ModuleName.Text = entMan.GetComponent<MetaDataComponent>(module).EntityName;

        var canRemove = entMan.TryGetComponent<ModModuleComponent>(module, out var mod) && !mod.Permanent;
        RemoveButton.TexturePath = "/Textures/Interface/Nano/cross.svg.png";
        RemoveButton.Visible = canRemove;

        RemoveButton.OnPressed += _ => RemoveButtonPressed?.Invoke();
    }
}
