using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Clothing.Modsuits.Components;
using Content.Shared.Containers;
using Content.Shared.Power.EntitySystems;
using Content.Shared.PowerCell;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Containers;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.Clothing.Modsuits;

[GenerateTypedNameReferences]
public sealed partial class ModSuitMenu : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly SharedContainerSystem _containers;
    private readonly PowerCellSystem _powerCell;
    private readonly SharedBatterySystem _battery;

    public Action? EjectBatteryButtonPressed;
    public Action<EntityUid>? RemoveModuleButtonPressed;

    private EntityUid _entity;
    private List<EntityUid> _modules = new();

    public ModSuitMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _entityManager = IoCManager.Resolve<IEntityManager>();
        _containers = _entityManager.System<SharedContainerSystem>();
        _powerCell = _entityManager.System<PowerCellSystem>();
        _battery = _entityManager.System<SharedBatterySystem>();

        EjectBatteryButton.OnPressed += _ => EjectBatteryButtonPressed?.Invoke();
    }

    public void SetEntity(EntityUid entity)
    {
        _entity = entity;
        UpdateUI();
    }

    public void UpdateUI()
    {
        if (!_entityManager.TryGetComponent<ModModuleContainerComponent>(_entity, out var container))
            return;

        if (!_containers.TryGetContainer(_entity, ModModuleContainerComponent.ContainerId, out var modContainer))
        {
            ModuleCounter.Text = Loc.GetString("mod-ui-module-counter",
                ("actual", 0),
                ("max", container.MaxModules));
            return;
        }

        var currentCount = modContainer.ContainedEntities.Count;
        ModuleCounter.Text = Loc.GetString("mod-ui-module-counter",
            ("actual", currentCount),
            ("max", container.MaxModules));

        if (currentCount == _modules.Count)
        {
            var isSame = true;
            foreach (var module in modContainer.ContainedEntities)
            {
                if (_modules.Contains(module))
                    continue;
                isSame = false;
                break;
            }

            if (isSame)
                return;
        }

        ModuleContainer.Children.Clear();
        _modules.Clear();

        foreach (var module in modContainer.ContainedEntities)
        {
            var control = new ModSuitModuleControl(module, _entityManager);
            control.RemoveButtonPressed += () =>
            {
                RemoveModuleButtonPressed?.Invoke(module);
            };
            ModuleContainer.AddChild(control);
            _modules.Add(module);
        }

        UpdateCharge();
    }

    public void UpdateCharge()
    {
        var chargeFraction = 0f;

        if (_powerCell.TryGetBatteryFromSlot(_entity, out var battery))
            chargeFraction = _battery.GetCharge(battery.Value.AsNullable()) / battery.Value.Comp.MaxCharge;

        ChargeBar.Value = chargeFraction;
        ChargeLabel.Text = Loc.GetString("mod-ui-charge-label",
            ("charge", (int)MathF.Round(chargeFraction * 100)));

        EjectBatteryButton.Disabled = !_powerCell.HasBattery(_entity);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateUI();
        UpdateCharge();
    }
}
