using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        BodyButton.OnPressed += _ => HealthAnalyzer.SelectDiagnosticTab(false);
        OrgansButton.OnPressed += _ => HealthAnalyzer.SelectDiagnosticTab(true);
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        HealthAnalyzer.Populate(msg.State);
    }
}
