using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        // <Onyx-HealthAnalyzerChemicals-edited>
        BodyButton.OnPressed += _ => HealthAnalyzer.SelectBodyTab();
        OrgansButton.OnPressed += _ => HealthAnalyzer.SelectOrgansTab();
        ChemicalsButton.OnPressed += _ => HealthAnalyzer.SelectChemicalsTab();
        // </Onyx-HealthAnalyzerChemicals-edited>
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        HealthAnalyzer.Populate(msg.State);
    }
}
