using Content.Shared._Onyx.Chemistry;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class EnergyReagentCardControl : Control
{
    public string ReagentId { get; }
    public float PowerCostPerUnit { get; }
    public bool IsDisabled => MainButton.Disabled;
    public Action<string>? OnPressed;

    public EnergyReagentCardControl(EnergyReagentInventoryItem item)
    {
        RobustXamlLoader.Load(this);
        ReagentId = item.Id;
        PowerCostPerUnit = item.Cost;
        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = item.Color };
        ReagentNameLabel.Text = item.Label;
        FillLabel.Text = $"{item.Cost}J/u";
        MainButton.OnPressed += _ => OnPressed?.Invoke(ReagentId);
    }

    public void SetDisabled(bool disabled, string tooltip = "")
    {
        Modulate = disabled ? Color.Gray : Color.White;
        MainButton.Disabled = disabled;
        ToolTip = disabled ? tooltip : null;
    }
}
