using Content.Client.UserInterface.Controls;
using Content.Client.Stylesheets;
using Content.Shared._Onyx.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Onyx.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class EnergyReagentDispenserWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private float _batteryCharge;
    private float _batteryMaxCharge;
    private float _currentReceiving;
    private float _idleUse;
    private bool _usingBattery;
    private bool _hasPower;
    private int _selectedAmount;
    private float _lastBatteryCharge = -1;
    private bool _cardsNeedUpdate = true;

    public event Action<string>? Dispense;

    public EnergyReagentDispenserWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(EnergyReagentDispenserBoundUserInterfaceState state)
    {
        _batteryCharge = state.Charge;
        _batteryMaxCharge = state.MaxCharge;
        _currentReceiving = state.Receiving;
        _idleUse = state.IdleUse;
        _usingBattery = state.UsingBattery;
        _hasPower = state.HasPower;
        _selectedAmount = (int) state.SelectedAmount;
        UpdateBatteryPercent();
        UpdateContainerInfo(state);
        ClearButton.Disabled = EjectButton.Disabled = state.OutputContainer is null;
        AmountGrid.Selected = ((int) state.SelectedAmount).ToString();
        _entityManager.TryGetEntity(state.OutputContainerEntity, out var outputContainer);
        View.SetEntity(outputContainer);
        ReagentList.Children.Clear();
        foreach (var item in state.Inventory)
        {
            var card = new EnergyReagentCardControl(item);
            card.OnPressed += Dispense;
            ReagentList.Children.Add(card);
        }
        _cardsNeedUpdate = true;
        UpdateCardStates();
    }

    private void UpdateBatteryPercent()
    {
        var percent = _batteryMaxCharge > 0 ? _batteryCharge / _batteryMaxCharge * 100 : 0;
        BatteryStatusLabel.Text = $"{_batteryCharge,3:F0}/{_batteryMaxCharge,3:F0} ({percent,3:F0}%)";
        BatteryStatusLabel.StyleClasses.Clear();
        BatteryStatusLabel.StyleClasses.Add(percent switch { > 60 => "Good", > 30 => "Caution", _ => "Danger" });
    }

    private void UpdateContainerInfo(EnergyReagentDispenserBoundUserInterfaceState state)
    {
        ContainerInfo.Children.Clear();
        if (state.OutputContainer is null)
        {
            ContainerInfoName.Text = "";
            ContainerInfoFill.Text = "";
            ContainerInfo.Children.Add(new Label { Text = Loc.GetString("reagent-dispenser-window-no-container-loaded-text") });
            return;
        }

        ContainerInfoName.Text = state.OutputContainer.DisplayName;
        ContainerInfoFill.Text = $"{state.OutputContainer.CurrentVolume}/{state.OutputContainer.MaxVolume}";
        foreach (var (reagent, quantity) in state.OutputContainer.Reagents!)
        {
            var localizedName = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto)
                ? proto.LocalizedName
                : Loc.GetString("reagent-dispenser-window-reagent-name-not-found-text");
            ContainerInfo.Children.Add(new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children = { new Label { Text = $"{localizedName}: " }, new Label { Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", quantity)), StyleClasses = { StyleClass.LabelWeak } } }
            });
        }
    }

    private void UpdateCardStates()
    {
        if (!_cardsNeedUpdate)
            return;

        var stateChanged = false;
        foreach (var child in ReagentList.Children)
        {
            if (child is not EnergyReagentCardControl card)
                continue;

            var shouldBeDisabled = card.PowerCostPerUnit * _selectedAmount > _batteryCharge;
            if (card.IsDisabled == shouldBeDisabled)
                continue;

            stateChanged = true;
            break;
        }

        if (!stateChanged && _lastBatteryCharge == _batteryCharge)
            return;

        _lastBatteryCharge = _batteryCharge;
        _cardsNeedUpdate = false;
        foreach (var child in ReagentList.Children)
        {
            if (child is EnergyReagentCardControl card)
                card.SetDisabled(card.PowerCostPerUnit * _selectedAmount > _batteryCharge, "Insufficient energy");
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var oldCharge = _batteryCharge;
        if (_usingBattery || !_hasPower)
            _batteryCharge = Math.Clamp(_batteryCharge - _idleUse * args.DeltaSeconds, 0, _batteryMaxCharge);
        else
            _batteryCharge = Math.Clamp(_batteryCharge + _currentReceiving * args.DeltaSeconds, 0, _batteryMaxCharge);

        if ((int) oldCharge != (int) _batteryCharge)
            UpdateBatteryPercent();

        foreach (var child in ReagentList.Children)
        {
            if (child is not EnergyReagentCardControl card)
                continue;

            var threshold = card.PowerCostPerUnit * _selectedAmount;
            if ((oldCharge < threshold && _batteryCharge >= threshold) ||
                (oldCharge >= threshold && _batteryCharge < threshold))
            {
                _cardsNeedUpdate = true;
                break;
            }
        }

        UpdateCardStates();
    }
}
