using System.Numerics;
using Content.Shared._Onyx.GPS;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client._Onyx.GPS;

[GenerateTypedNameReferences]
public sealed partial class CompassControl : LayoutContainer
{
    [Dependency] private IEyeManager _eyeManager = default!;

    private MapCoordinates _gpsCoordinates;
    private NetEntity? _trackedEntity;
    private List<GpsEntry> _gpsEntries = new();
    private float _zoom = 6f;

    private const float GridLinesPerMeter = 4f;
    private const int GridMetersPerZoom = 16;
    private const float DotRadius = 3f;
    private const float SelectedDotRadius = 6f;
    private const float DistressDotRadius = 5f;
    private const float ScrollSensitivity = 8f;

    public float MinZoom = 1f;
    public float MaxZoom = 10f;

    private float GridLines => GridMetersPerZoom * _zoom;

    public CompassControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Pass;
    }

    public void SetState(MapCoordinates gpsCoordinates, NetEntity? trackedEntity, List<GpsEntry> gpsEntries)
    {
        _gpsCoordinates = gpsCoordinates;
        _trackedEntity = trackedEntity;
        _gpsEntries = gpsEntries;
    }

    public void UpdatePosition(MapCoordinates gpsCoordinates)
    {
        _gpsCoordinates = gpsCoordinates;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        var gridSize = Math.Min(PixelSize.X, PixelSize.Y) * 0.9f;
        var center = UIBox2.FromDimensions(Vector2.Zero, PixelSize).Center;
        var halfSize = gridSize / 2;
        var topLeft = center - new Vector2(halfSize);
        var bottomRight = center + new Vector2(halfSize);
        handle.DrawRect(new UIBox2(topLeft, bottomRight), Color.Black.WithAlpha(0.5f));

        var cellStep = gridSize / GridLines * GridLinesPerMeter;
        for (var i = 0; i <= GridLines / GridLinesPerMeter; i++)
        {
            var vertical = topLeft + new Vector2(i * cellStep, 0);
            handle.DrawLine(vertical, vertical + new Vector2(0, gridSize), Color.White.WithAlpha(0.2f));
            var horizontal = topLeft + new Vector2(0, i * cellStep);
            handle.DrawLine(horizontal, horizontal + new Vector2(gridSize, 0), Color.White.WithAlpha(0.2f));
        }

        handle.DrawRect(new UIBox2(topLeft, bottomRight), Color.White, false);
        handle.DrawCircle(center, DotRadius, Color.Cyan);
        var gridScale = gridSize / GridLines;

        foreach (var entry in _gpsEntries)
        {
            if (entry.Coordinates.MapId != _gpsCoordinates.MapId)
                continue;

            var screen = _eyeManager.CurrentEye.Rotation.RotateVec(entry.Coordinates.Position - _gpsCoordinates.Position);
            screen.Y = -screen.Y;
            var position = center + screen * gridScale;
            position.X = Math.Clamp(position.X, topLeft.X, bottomRight.X);
            position.Y = Math.Clamp(position.Y, topLeft.Y, bottomRight.Y);
            var selected = _trackedEntity == entry.NetEntity;
            var radius = selected ? SelectedDotRadius : entry.IsDistress ? DistressDotRadius : DotRadius;
            var color = selected ? Color.Cyan : entry.IsDistress ? Color.Pink : entry.Color;
            handle.DrawCircle(position, radius, color);
        }
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);
        _zoom = Math.Clamp(_zoom - args.Delta.Y / ScrollSensitivity * _zoom, MinZoom, MaxZoom);
    }
}
