using System.Linq;
using System.Numerics;
using Content.Client.Resources;
using Content.Shared._Onyx.GPS;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.GPS;

[GenerateTypedNameReferences]
public sealed partial class GpsWindow : BaseWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IResourceCache _cache = default!;
    [Dependency] private IGameTiming _timing = default!;

    private readonly SharedTransformSystem _transform;
    private readonly SpriteSystem _sprite;
    private readonly Texture _distressSprite;
    private EntityUid _owner;
    private bool _inDistress;
    private bool _enabled;
    private bool _editingName;
    private bool _settingName;
    private string? _lastEnteredText;
    private List<GpsEntry> _previousEntries = new();

    public event Action<NetEntity?>? TrackedEntitySelected;
    public event Action<string>? GpsNameChanged;
    public event Action<bool>? DistressPressed;
    public event Action<bool>? EnabledPressed;

    public GpsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _distressSprite = _cache.GetTexture("/Textures/_Onyx/Interface/GPS/distress.png");
        _transform = _entityManager.System<SharedTransformSystem>();
        _sprite = _entityManager.System<SpriteSystem>();
        ClearButton.OnPressed += _ => TrackedEntitySelected?.Invoke(null);
        GpsName.OnTextEntered += args =>
        {
            _editingName = false;
            _lastEnteredText = args.Text[..Math.Min(args.Text.Length, SharedGpsSystem.MaxNameLength)];
            GpsName.Text = _lastEnteredText;
            GpsNameChanged?.Invoke(_lastEnteredText);
        };
        GpsName.OnTextChanged += args =>
        {
            if (!_settingName)
                _editingName = true;
        };
        DistressButton.OnPressed += _ => DistressPressed?.Invoke(!_inDistress);
        EnabledButton.OnPressed += _ => EnabledPressed?.Invoke(!_enabled);
        CloseButton.OnPressed += _ => Close();
    }

    public void UpdateState(EntityUid owner, GpsUpdateMessage gps)
    {
        if (!_editingName)
            _lastEnteredText = gps.GpsName;
        _inDistress = gps.InDistress;
        _enabled = gps.Enabled;
        _owner = owner;
        EnabledButton.Text = Loc.GetString(gps.Enabled ? "gps-window-visibility-on" : "gps-window-visibility-off");
        DistressButton.ModulateSelfOverride = gps.InDistress ? Color.Red : null;
        if (!_editingName)
        {
            _settingName = true;
            GpsName.Text = _lastEnteredText ?? string.Empty;
            _settingName = false;
        }
        UpdateTrackedEntity(gps.Entries, gps.TrackedEntity);
        UpdateGpsEntries(gps.Entries, gps.TrackedEntity);
        var coordinates = _transform.GetMapCoordinates(_owner);
        CompassContainer.SetState(coordinates, gps.TrackedEntity, gps.Entries);
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    public void SetPendingTrackedEntity(NetEntity? trackedEntity)
    {
        UpdateSelectedEntry(trackedEntity);
    }

    public void SetPendingDistress(bool inDistress)
    {
        _inDistress = inDistress;
        DistressButton.ModulateSelfOverride = inDistress ? Color.Red : null;
    }

    public void SetPendingEnabled(bool enabled)
    {
        _enabled = enabled;
        EnabledButton.Text = Loc.GetString(enabled ? "gps-window-visibility-on" : "gps-window-visibility-off");
    }

    private void UpdateTrackedEntity(List<GpsEntry> entries, NetEntity? trackedEntity)
    {
        var tracked = trackedEntity == null ? null : entries.FirstOrDefault(entry => entry.NetEntity == trackedEntity);
        TrackedPositionLabel.Text = tracked != null
            ? $"{tracked.Coordinates.X:F0}, {tracked.Coordinates.Y:F0}"
            : Loc.GetString(trackedEntity == null ? "gps-window-position-none" : "gps-window-position-unknown");
    }

    private void UpdateGpsEntries(List<GpsEntry> entries, NetEntity? trackedEntity)
    {
        var sorted = entries
            .OrderByDescending(entry => entry.IsDistress)
            .ThenBy(entry => entry.PrototypeId is { } prototypeId &&
                _prototypes.Index<EntityPrototype>(prototypeId).Components.ContainsKey("NavMapBeacon"))
            .ThenBy(entry => entry.Name)
            .ToList();

        if (sorted.SequenceEqual(_previousEntries))
        {
            UpdateSelectedEntry(trackedEntity);
            return;
        }

        _previousEntries = sorted;
        GpsList.DisposeAllChildren();
        foreach (var entry in sorted)
        {
            IRsiStateLike? icon = entry.IsDistress
                ? _distressSprite
                : entry.PrototypeId is { } prototypeId
                    ? _sprite.GetPrototypeIcon(prototypeId).Default
                    : null;
            var item = new GpsListEntry(entry.Name ?? Loc.GetString("generic-unknown-title"), entry.NetEntity, icon, entry.Color);
            item.OnPressed += _ => TrackedEntitySelected?.Invoke(entry.NetEntity);
            GpsList.AddChild(item);
        }
        UpdateSelectedEntry(trackedEntity);
    }

    private void UpdateSelectedEntry(NetEntity? trackedEntity)
    {
        foreach (var child in GpsList.Children)
            ((GpsListEntry) child).Pressed = trackedEntity == ((GpsListEntry) child).TrackedEntity;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (!_entityManager.TryGetComponent(_owner, out TransformComponent? xform))
            return;

        var coordinates = _transform.GetMapCoordinates(_owner, xform);
        GpsPositionLabel.Text = $"{coordinates.Position.X:F0}, {coordinates.Position.Y:F0}";
        CompassContainer.UpdatePosition(coordinates);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
