using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using SixLabors.ImageSharp;
using System.IO;
using System.Numerics;

namespace Content.Client._CorvaxGoob.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotoCameraWindow : FancyWindow
{
    [Dependency] private IResourceCache _cache = default!;

    public Vector2 MoveInput = Vector2.Zero;
    public float ZoomInput;
    public event Action? OnTakeImageAttempt;

    public PhotoCameraWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CameraView.ViewportSize = new Vector2i(250, 250);
        PhotoButton.BaseTexture = new SpriteSpecifier.Texture(new("/Textures/_CorvaxGoob/Interface/Misc/Photo/button_base.png"));
        PhotoButton.PointedTexture = new SpriteSpecifier.Texture(new("/Textures/_CorvaxGoob/Interface/Misc/Photo/button_highlight.png"));
        PhotoButton.PressedTexture = new SpriteSpecifier.Texture(new("/Textures/_CorvaxGoob/Interface/Misc/Photo/button_pressed.png"));
        PhotoButton.ShowBase();

        if (_cache.TryGetResource("/Audio/Items/Stamp/automatic_stamp.ogg", out AudioResource? resource))
            PhotoButton.ClickSound = resource;

        PhotoButton.OnPressed += _ => OnTakeImageAttempt?.Invoke();
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);
        ZoomInput = -args.Delta.Y;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);
        HandleMoveKey(args.Function, 1);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);
        HandleMoveKey(args.Function, -1);
    }

    private void HandleMoveKey(BoundKeyFunction function, float delta)
    {
        if (function == EngineKeyFunctions.MoveUp)
            MoveInput.Y += delta;
        if (function == EngineKeyFunctions.MoveDown)
            MoveInput.Y -= delta;
        if (function == EngineKeyFunctions.MoveRight)
            MoveInput.X += delta;
        if (function == EngineKeyFunctions.MoveLeft)
            MoveInput.X -= delta;
    }

    public void UpdateState(IEye? eye, bool hasPaper)
    {
        CameraView.Eye = eye;
        PaperIndicator.TexturePath = $"/Textures/_CorvaxGoob/Interface/Misc/Photo/paper_{(hasPaper ? "on" : "off")}.png";
    }

    public void RenderImage(Action<byte[]?> callback)
    {
        CameraView.Screenshot(image =>
        {
            // <Onyx-PhotoCamera-edited>
            using (image)
            {
                byte[] data;
                try
                {
                    using var stream = new MemoryStream();
                    image.SaveAsPng(stream);
                    data = stream.ToArray();
                }
                catch
                {
                    callback(null);
                    return;
                }

                callback(data);
            }
            // </Onyx-PhotoCamera-edited>
        });
    }

    public void OnDispose()
    {
        PhotoButton.ClickSound = null;
    }
}
