using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.IO;
using System.Numerics;

namespace Content.Client._CorvaxGoob.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotoCardWindow : BaseWindow
{
    private const int DragMarginSize = 16;
    private OwnedTexture? _imageTexture;

    public PhotoCardWindow()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += _ => Close();
    }

    public void ShowImage(byte[] imageData)
    {
        try
        {
            using var stream = new MemoryStream(imageData);
            var texture = (OwnedTexture) Texture.LoadFromPNGStream(stream, "Photo card");
            _imageTexture?.Dispose();
            _imageTexture = texture;
            ImageDisplay.Texture = texture;
        }
        catch
        {
            // Invalid image data is ignored; the server validates the PNG signature before storing it.
        }
    }

    protected override void ExitedTree()
    {
        ImageDisplay.Texture = null;
        _imageTexture?.Dispose();
        _imageTexture = null;
        base.ExitedTree();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.None;
        if (relativeMousePos.Y < DragMarginSize)
            mode |= DragMode.Top;
        else if (relativeMousePos.Y > Size.Y - DragMarginSize)
            mode |= DragMode.Bottom;

        if (relativeMousePos.X < DragMarginSize)
            mode |= DragMode.Left;
        else if (relativeMousePos.X > Size.X - DragMarginSize)
            mode |= DragMode.Right;

        return mode == DragMode.None ? DragMode.Move : mode;
    }
}
