using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Sources;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client._CorvaxGoob.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class TextureButton : ContainerButton
{
    [Dependency] private IAudioManager _audioManager = default!;

    private IAudioSource? _clickSound;
    public SpriteSpecifier? BaseTexture;
    public SpriteSpecifier? PointedTexture;
    public SpriteSpecifier? PressedTexture;

    public TextureButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Icon.DisplayRect.Stretch = TextureRect.StretchMode.Scale;

        OnMouseEntered += _ => SetTexture(PointedTexture);
        OnMouseExited += _ => SetTexture(BaseTexture);
        OnButtonDown += _ =>
        {
            SetTexture(PressedTexture);
            _clickSound?.Restart();
        };
        OnButtonUp += _ => SetTexture(PointedTexture);
    }

    public Vector2 TextureScale
    {
        get => Icon.DisplayRect.TextureSizeTarget;
        set => Icon.DisplayRect.SetSize = value;
    }

    public AudioResource? ClickSound
    {
        set
        {
            _clickSound?.Dispose();
            _clickSound = value == null ? null : _audioManager.CreateAudioSource(value);
            if (_clickSound != null)
                _clickSound.Global = true;
        }
    }

    public void ShowBase()
    {
        SetTexture(BaseTexture);
    }

    private void SetTexture(SpriteSpecifier? texture)
    {
        if (texture != null)
            Icon.SetFromSpriteSpecifier(texture);
    }
}
