using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Onyx.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyVendingMachineItem : BoxContainer
{
    public Action? BuyPressed;

    public FancyVendingMachineItem(EntProtoId entProto, string text, int count, int price)
    {
        RobustXamlLoader.Load(this);
        BuyButton.OnPressed += _ => BuyPressed?.Invoke();

        BuyButton.Disabled = count <= 0;

        ItemPrototype.SetPrototype(entProto);

        NameLabel.Text = text;
        CountLabel.SetMarkup(Loc.GetString("vending-machine-ui-count", ("count", count), ("color", count > 0 ? "[color=white]" : "[color=red]")));

        var priceText = price <= 0 ? Loc.GetString("vending-machine-ui-price-free") : Loc.GetString("vending-machine-ui-price", ("price", price));
        CostLabel.SetMarkup(priceText);
    }
}
