using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Weapons.AmmoSelector;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Onyx.Weapons.AmmoSelector;

[GenerateTypedNameReferences]
public sealed partial class AmmoSelectorMenu : RadialMenu
{
    [Dependency] private EntityManager _entities = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;

    private readonly SpriteSystem _sprites;

    public event Action<ProtoId<SelectableAmmoPrototype>>? AmmoSelected;

    public AmmoSelectorMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _sprites = _entities.System<SpriteSystem>();
    }

    public void SetEntity(EntityUid uid)
    {
        Main.RemoveAllChildren();
        if (!_entities.TryGetComponent(uid, out AmmoSelectorComponent? selector))
            return;

        foreach (var id in selector.Prototypes)
        {
            if (!_prototypes.TryIndex(id, out var prototype))
                continue;

            var button = new AmmoSelectorMenuButton
            {
                SetSize = new Vector2(64, 64),
                ToolTip = Loc.GetString("asmb-desc-" + prototype.ID),
                Prototype = id
            };
            button.AddChild(new TextureRect
            {
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                Texture = _sprites.Frame0(prototype.Icon),
                TextureScale = new Vector2(2f, 2f)
            });
            button.OnButtonUp += _ =>
            {
                AmmoSelected?.Invoke(button.Prototype);
                Close();
            };
            Main.AddChild(button);
        }
    }
}

public sealed class AmmoSelectorMenuButton : RadialMenuButtonWithSector
{
    public ProtoId<SelectableAmmoPrototype> Prototype { get; set; }
}
