using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.FireControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.FireControl.UI;

[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    public FireControlNavControl Radar => NavRadar;
    public event Action? OnServerRefresh;

    private readonly Dictionary<NetEntity, Button> _weapons = new();

    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        SelectAllButton.OnPressed += _ => SetAll(true);
        UnselectAllButton.OnPressed += _ => SetAll(false);
    }

    public List<NetEntity> GetSelectedWeapons()
    {
        return _weapons.Where(pair => pair.Value.Pressed).Select(pair => pair.Key).ToList();
    }

    public void UpdateStatus(FireControlConsoleBoundInterfaceState state)
    {
        NavRadar.UpdateState(state.NavState);
        NavRadar.SetControllables(state.FireControllables);
        ServerStatus.Text = Loc.GetString(state.Connected ? "gunnery-window-connected" : "gunnery-window-disconnected");
        ServerStatus.FontColorOverride = state.Connected ? Color.Green : Color.Red;

        var removed = _weapons.Keys.ToHashSet();
        foreach (var controllable in state.FireControllables)
        {
            if (_weapons.ContainsKey(controllable.NetEntity))
            {
                removed.Remove(controllable.NetEntity);
                continue;
            }

            var button = new Button
            {
                ToggleMode = true,
                Text = controllable.Name,
                HorizontalExpand = true,
                Margin = new Thickness(4, 1),
            };
            button.OnToggled += _ => UpdateAimPreview();
            _weapons.Add(controllable.NetEntity, button);
            ControllablesBox.AddChild(button);
        }

        foreach (var entity in removed)
        {
            ControllablesBox.RemoveChild(_weapons[entity]);
            _weapons.Remove(entity);
        }

        SelectAllButton.Disabled = _weapons.Count == 0;
        UnselectAllButton.Disabled = _weapons.Count == 0;
    }

    private void SetAll(bool pressed)
    {
        foreach (var button in _weapons.Values)
            button.Pressed = pressed;

        UpdateAimPreview();
    }

    private void UpdateAimPreview()
    {
        NavRadar.SetSelectedWeapons(_weapons.Where(pair => pair.Value.Pressed).Select(pair => pair.Key));
    }
}
