using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Botany.PlantAnalyzer;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.Botany.PlantAnalyzer;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly IGameTiming _gameTiming;
    private readonly PlantAnalyzerLocalizationHelper _localizationHelper;

    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        _entityManager = IoCManager.Resolve<IEntityManager>();
        _gameTiming = IoCManager.Resolve<IGameTiming>();
        _localizationHelper = _entityManager.System<PlantAnalyzerLocalizationHelper>();
    }

    public void Populate(PlantAnalyzerScannedUserMessage msg)
    {
        Print.Disabled = !msg.ScanMode.GetValueOrDefault() ||
                         msg.PrintReadyAt.GetValueOrDefault(TimeSpan.MaxValue) > _gameTiming.CurTime ||
                         msg.PlantData is null;
        var target = _entityManager.GetEntity(msg.TargetEntity);
        if (target is null)
            return;

        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = msg.ScanMode == true;
        NoDataIcon.Visible = !SpriteView.Visible;
        ScanModeLabel.Text = msg.ScanMode.HasValue
            ? msg.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");
        ScanModeLabel.FontColorOverride = msg.ScanMode == true ? Color.Green : Color.Red;
        SeedLabel.Text = msg.PlantData == null
            ? Loc.GetString("plant-analyzer-component-no-seed")
            : Loc.GetString(msg.PlantData.SeedDisplayName);
        ContainerLabel.Text = Identity.Name(target.Value, _entityManager);

        if (msg.PlantData is { } plant)
        {
            Health.Text = plant.Health.ToString("0.00");
            Endurance.Text = plant.Endurance.ToString("0.00");
            Age.Text = plant.Age.ToString("0.00");
            Lifespan.Text = plant.Lifespan.ToString("0.00");
            Dead.Visible = plant.Dead;
            Alive.Visible = !plant.Dead;
            Unviable.Visible = !plant.Viable;
            Mutating.Visible = plant.Mutating;
            Kudzu.Visible = plant.Kudzu;
            PlantDataGrid.Visible = true;
        }
        else
            PlantDataGrid.Visible = false;

        PlantDataTags.Visible = PlantDataGrid.Visible;
        PlantDataDivider.Visible = PlantDataGrid.Visible;

        if (msg.TrayData is { } tray)
        {
            WaterLevelLabel.Text = tray.WaterLevel.ToString("0.00");
            NutritionLevelLabel.Text = tray.NutritionLevel.ToString("0.00");
            ToxinsLabel.Text = tray.Toxins.ToString("0.00");
            PestLevelLabel.Text = tray.PestLevel.ToString("0.00");
            WeedLevelLabel.Text = tray.WeedLevel.ToString("0.00");
            if (msg.TolerancesData is { } tolerances)
            {
                GtFieldIfTolerances1.Text = ">";
                LtFieldIfTolerances1.Text = "<";
                WaterConsumptionLabel.Text = tolerances.WaterConsumption.ToString("0.00");
                NutritionConsumptionLabel.Text = tolerances.NutrientConsumption.ToString("0.00");
                ToxinsResistanceLabel.Text = tolerances.ToxinsTolerance.ToString("0.00");
                PestResistanceLabel.Text = tolerances.PestTolerance.ToString("0.00");
                WeedResistanceLabel.Text = tolerances.WeedTolerance.ToString("0.00");
            }
            else
            {
                GtFieldIfTolerances1.Text = LtFieldIfTolerances1.Text = "";
                WaterConsumptionLabel.Text = NutritionConsumptionLabel.Text = ToxinsResistanceLabel.Text = "";
                PestResistanceLabel.Text = WeedResistanceLabel.Text = "";
            }
            GtFieldIfTolerances2.Text = GtFieldIfTolerances1.Text;
            LtFieldIfTolerances2.Text = LtFieldIfTolerances3.Text = LtFieldIfTolerances1.Text;
            ContainerGrid.Visible = true;
        }
        else
            ContainerGrid.Visible = false;
        ContainerDivider.Visible = ContainerGrid.Visible;

        if (msg.TrayData?.Chemicals is { } soilChemicals)
        {
            ChemicalsInWaterLabel.Text = soilChemicals.Count == 0
                ? Loc.GetString("plant-analyzer-soil-empty", ("holder", ContainerLabel.Text))
                : Loc.GetString("plant-analyzer-soil",
                    ("count", soilChemicals.Count),
                    ("holder", ContainerLabel.Text),
                    ("chemicals", _localizationHelper.ChemicalsToLocalizedStrings(soilChemicals)));
            ChemicalsInWaterBox.Visible = true;
        }
        else
            ChemicalsInWaterBox.Visible = false;
        ChemicalsInWaterDivider.Visible = ChemicalsInWaterBox.Visible;

        if (msg.TolerancesData is { } environment)
        {
            (string, string)[] parameters =
            [
                ("seedName", SeedLabel.Text),
                ("gases", _localizationHelper.GasesToLocalizedStrings(environment.ConsumeGasses)),
                ("kpa", environment.IdealPressure.ToString("0.00")),
                ("kpaTolerance", environment.PressureTolerance.ToString("0.00")),
                ("temp", environment.IdealHeat.ToString("0.00")),
                ("tempTolerance", environment.HeatTolerance.ToString("0.00")),
                ("lightLevel", environment.IdealLight.ToString("0.00")),
                ("lightTolerance", environment.LightTolerance.ToString("0.00")),
            ];
            EnvironmentLabel.Text = environment.ConsumeGasses.Count == 0
                ? environment.IdealHeat - environment.HeatTolerance <= 0f && environment.IdealPressure - environment.PressureTolerance <= 0f
                    ? Loc.GetString("plant-analyzer-component-environemt-void", [.. parameters])
                    : Loc.GetString("plant-analyzer-component-environemt", [.. parameters])
                : Loc.GetString("plant-analyzer-component-environemt-gas", [.. parameters]);
            EnvironmentBox.Visible = true;
        }
        else
            EnvironmentBox.Visible = false;
        EnvironmentDivider.Visible = EnvironmentBox.Visible;

        if (msg.ProduceData is { } produce)
        {
            var localizedProduce = _localizationHelper.ProduceToLocalizedStrings(produce.Produce);
            (string, object)[] parameters =
            [
                ("yield", produce.Yield),
                ("gasCount", produce.ExudeGasses.Count),
                ("gases", _localizationHelper.GasesToLocalizedStrings(produce.ExudeGasses)),
                ("potency", Loc.GetString(produce.Potency)),
                ("seedless", produce.Seedless),
                ("firstProduce", localizedProduce.First),
                ("produce", localizedProduce.Singular),
                ("producePlural", localizedProduce.Plural),
                ("chemCount", produce.Chemicals.Count),
                ("chemicals", _localizationHelper.ChemicalsToLocalizedStrings(produce.Chemicals)),
                ("nothing", ""),
            ];
            ProduceLabel.Text = Loc.GetString("plant-analyzer-output", parameters);
            ProduceBox.Visible = true;
        }
        else
            ProduceBox.Visible = false;
        ProduceDivider.Visible = ProduceBox.Visible;
    }
}
