using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Salvage.MarkerBeacon;

[GenerateTypedNameReferences]
public sealed partial class MarkerBeaconColorPickerWindow : FancyWindow
{
    private readonly ColorSelectorSliders _selector;
    public event Action<Color, bool>? OnConfirm;

    public MarkerBeaconColorPickerWindow()
    {
        RobustXamlLoader.Load(this);
        _selector = new ColorSelectorSliders { SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv };
        ColorContainer.AddChild(_selector);
        Confirm.OnPressed += _ => OnConfirm?.Invoke(_selector.Color, RgbCycle.Pressed);
    }

    public void SetState(Color color, bool hacked)
    {
        _selector.Color = color;
        RgbCycle.Pressed = hacked;
    }
}
